/** Deutsch — maschinell übersetzt, nur oberflächlich geprüft. */
export const de: Record<string, string> = {
  'state.noName': 'Ohne Namen',
  'main.tab.passes': 'Pässe',
  'main.tab.generate': 'Erzeugen',
  'main.tab.wii': 'Wii',
  'main.editPass': 'Pass bearbeiten',
  'dom.accept': 'Akzeptieren',
  'dom.cancel': 'Abbrechen',
  'dom.nothingToPick': 'Es gibt nichts zur Auswahl.',
  'dom.preparing': 'Wird vorbereitet…',
  'dom.sizeOf': '{loaded} von {total}',
  'wii.phase.nand': 'Die Wii liest ihren Spielstand…',
  'wii.phase.data': 'Übertragung läuft…',
  'wii.phase.saving': 'Die Wii schreibt auf den NAND-Speicher. Nicht ausschalten.',
  'wii.sessionLost': 'Die Sitzung mit der Wii ist verloren gegangen',
  'wii.busyTitle': 'Ein anderes Gerät hat die Sitzung',
  'wii.busyStale': 'Seit {idle} s ohne Lebenszeichen; sie läuft in {remaining} s von selbst ab. Meist ist es ein geschlossener Tab, dessen Hinweis die Wii nie erreicht hat: du kannst sie jetzt übernehmen.',
  'wii.busyActive': 'Ein anderes Gerät bearbeitet gerade und ist aktiv (letztes Signal vor {idle} s). Ist wirklich niemand da, wird sie in {remaining} s frei.',
  'wii.takeover': 'Übernehmen',
  'wii.contactLost': 'Kein Kontakt zur Wii; neuer Versuch',
  'wii.contactBack': 'Kontakt zur Wii wiederhergestellt',
  'wii.releaseNote': 'Letztes Schließen: {when} ({event}) — {what}',
  'wii.releaseSent': 'Schließhinweis an die Wii gesendet',
  'wii.releaseFallback': 'Browser hat den Beacon abgelehnt; mit fetch versucht',
  'wii.releaseNothing': 'es gab keine Sitzung zum Freigeben',
  'wii.enterAddress': 'Gib die Adresse der Wii ein',
  'wii.badAddress': 'Diese Adresse ist ungültig. Gib die IP der Wii oder ihren Namen ein (zum Beispiel wii.local).',
  'wii.readingFromWii': 'Spielstand der Wii wird gelesen',
  'wii.readFromWii': 'Spielstand von der Wii gelesen ({count} Profile)',
  'wii.cannotConnect': 'Verbindung nicht möglich',
  'wii.loaded': 'Spielstand geladen: {count} Profile',
  'wii.notAPbrSave': 'Die Datei ist kein PBR-Spielstand',
  'wii.savedLocally': '{count} Pässe lokal gespeichert',
  'wii.nothingSaved': 'Es wurde nichts gespeichert (voll?)',
  'wii.selectInPassesTab': 'Wähle Pässe im Reiter Pässe aus',
  'wii.chooseNSlots': 'Wähle {count} Zielplätze',
  'wii.overwriteTitle': 'Du überschreibst Pässe',
  'wii.overwriteBody': '{count} der gewählten Plätze haben bereits einen Pass: {names}. Diese gehen verloren.',
  'wii.overwrite': 'Überschreiben',
  'wii.slotN': 'Platz {n}',
  'wii.written': '{count} Pässe in den Spielstand geschrieben. Denk daran, ihn an die Wii zu senden.',
  'wii.save': 'Spielstand',
  'wii.loadHint': 'Lade den Spielstand aus einer Datei, oder verbinde dich mit dem Wii-Assistenten, falls er läuft.',
  'wii.sameNetwork': 'Dieses Gerät muss im selben lokalen Netzwerk sein wie die Wii. Eine öffentliche IP mit Portweiterleitung funktioniert nicht.',
  'wii.wiiAddress': 'Adresse der Wii',
  'wii.port': 'Port',
  'wii.connecting': 'Verbindung wird hergestellt…',
  'wii.connect': 'Mit der Wii verbinden',
  'wii.openFile': 'Datei öffnen',
  'wii.source': 'Quelle: {source}',
  'wii.editSessionOpen': 'Bearbeitungssitzung geöffnet',
  'wii.partition': 'Partition {n}',
  'wii.saveNumber': 'Spielstand Nr. {n}',
  'wii.gameVersion': '{version} Fassung · {lang}',
  'wii.version.jp': 'japanische',
  'wii.version.int': 'internationale',
  'wii.profile': 'Profil',
  'wii.emptyFile': 'Datei {n} (leer)',
  'wii.close': 'Schließen',
  'wii.downloadBackup': 'Originalkopie herunterladen',
  'wii.queueTitle': 'Zu übertragende Pässe',
  'wii.queueEmpty': 'Noch keiner. Gehe zum Reiter Pässe und markiere die gewünschten mit dem Kreis in der Ecke oder durch langes Drücken.',
  'wii.noSlot': 'kein Platz',
  'wii.toSlot': '→ Platz {n}',
  'wii.removeFromTransfer': 'Aus der Übertragung entfernen',
  'wii.markOneMoreSlot': 'Markiere unten {count} weiteren Platz: Sie werden in der Reihenfolge zugewiesen, in der du sie berührst.',
  'wii.markNMoreSlots': 'Markiere unten {count} weitere Plätze: Sie werden in der Reihenfolge zugewiesen, in der du sie berührst.',
  'wii.allSlotsPaired': 'Jeder Pass hat bereits seinen Platz. Überprüfe die Ziele vor der Übertragung.',
  'wii.passesInSave': 'Pässe im Spielstand ({used} von {total} persönlichen)',
  'wii.design': 'Design {n}',
  'wii.locked': 'gesperrt',
  'wii.unused': 'unbenutzt',
  'wii.replaces': 'ersetzt {name}',
  'wii.theSlotN': 'Platz {n}',
  'wii.actions': 'Aktionen',
  'wii.saveNLocally': '{n} lokal speichern',
  'wii.transfer': 'Übertragen',
  'wii.transferNToSlots': '{n} auf ihre Plätze übertragen',
  'wii.selectFirstHint': 'Wähle zum Übertragen zuerst Pässe im Reiter Pässe aus.',
  'wii.transferSummary': '{passes} · {slots} — {status}',
  'wii.nPassOne': '{n} Pass',
  'wii.nPassMany': '{n} Pässe',
  'wii.nSlotOne': '{n} Platz zugewiesen',
  'wii.nSlotMany': '{n} Plätze zugewiesen',
  'wii.missingOne': '{n} fehlt',
  'wii.missingMany': '{n} fehlen',
  'wii.allReady': 'alles bereit',
  'wii.unlock': 'Freischalten',
  'wii.unlockHint': 'Passplätze und Kolosseen werden normalerweise durch Spielen freigeschaltet. Dies überspringt das.',
  'wii.unlockSlotsTitle': 'Passplätze freischalten',
  'wii.unlockSlotsBody': 'Die {n} persönlichen Passplätze dieses Profils werden als verfügbar markiert.',
  'wii.unlock.button': 'Freischalten',
  'wii.slotsUnlocked': 'Passplätze freigeschaltet',
  'wii.allSlots': 'Alle Plätze',
  'wii.unlockColosseumsTitle': 'Kolosseen freischalten',
  'wii.unlockColosseumsBody': 'Alle zehn Kolosseen werden in diesem Profil als freigeschaltet markiert.',
  'wii.colosseumsUnlocked': 'Kolosseen freigeschaltet',
  'wii.allColosseums': 'Alle Kolosseen',
  'wii.send': 'Senden',
  'wii.sendHint': 'Beim Senden werden die Prüfsummen neu berechnet und der Zähler erhöht, damit das Spiel diesen Spielstand bevorzugt.',
  'wii.sessionOpenHint': 'Solange dieser Bildschirm geöffnet bleibt, kann kein anderes Gerät den Spielstand bearbeiten. Drücke am Ende auf Schließen.',
  'wii.downloadSave': 'Spielstand herunterladen',
  'wii.sendToWiiTitle': 'An die Wii senden',
  'wii.sendToWiiBody': 'Der Spielstand der Wii wird überschrieben. Stelle sicher, dass du vorher die Originalkopie heruntergeladen hast.',
  'wii.send.button': 'Senden',
  'wii.noSession': 'Es besteht keine offene Sitzung mit der Wii',
  'wii.sendingToWii': 'Spielstand wird an die Wii gesendet',
  'wii.sentToWii': 'Spielstand an die Wii gesendet',
  'wii.cannotSend': 'Senden nicht möglich',
  'wii.sendToWii': 'An die Wii senden',
  'pokemoneditor.stat.hp': 'KP',
  'pokemoneditor.stat.atk': 'Ang',
  'pokemoneditor.stat.def': 'Vert',
  'pokemoneditor.stat.spa': 'SpAng',
  'pokemoneditor.stat.spd': 'SpVert',
  'pokemoneditor.stat.spe': 'Init',
  'pokemoneditor.noItem': '— keins —',
  'pokemoneditor.male': 'Männlich',
  'pokemoneditor.female': 'Weiblich',
  'pokemoneditor.back': '‹ Zurück',
  'pokemoneditor.noPidForGender': 'Für dieses Pokémon wurde keine PID mit diesem Geschlecht gefunden',
  'pokemoneditor.level': 'Lvl. {level}',
  'pokemoneditor.shinyBadge': 'schillernd',
  'pokemoneditor.shinyLabel': 'Schillernd',
  'pokemoneditor.species': 'Spezies',
  'pokemoneditor.nickname': 'Spitzname',
  'pokemoneditor.own': 'eigener',
  'pokemoneditor.nature': 'Wesen',
  'pokemoneditor.noPidForNature': 'Für dieses Pokémon wurde keine PID mit diesem Wesen gefunden',
  'pokemoneditor.ability': 'Fähigkeit',
  'pokemoneditor.item': 'Item',
  'pokemoneditor.pidNotHex': 'Die PID besteht aus 8 Hexadezimalstellen',
  'pokemoneditor.random': 'Zufällig',
  'pokemoneditor.pidHint': 'Aus ihr ergeben sich Wesen, Geschlecht und welche Fähigkeit das Spiel verwendet.',
  'pokemoneditor.abilityMismatch': '⚠ Das niedrige Bit der PID verlangt {ability}. Das Spiel respektiert die gespeicherte Fähigkeit, aber eine Legalitätsprüfung würde dies markieren.',
  'pokemoneditor.moves': 'Attacken',
  'pokemoneditor.recommended': 'Empfohlen',
  'pokemoneditor.recommendedHint': 'die, die das Spiel auf Level 50 vergeben würde',
  'pokemoneditor.emptySlot': '— leer —',
  'pokemoneditor.allowIllegal': 'Illegale Attacken erlauben',
  'pokemoneditor.noDamagingMove': 'Keine Attacke verursacht Schaden.',
  'pokemoneditor.stats': 'Statuswerte',
  'pokemoneditor.statsHint': 'Die EPs werden verteilt (insgesamt 510). Die IWs sind von Geburt an fest: 31 ist das Maximum.',
  'pokemoneditor.ev': 'EP',
  'pokemoneditor.evOf510': 'EP: {total} / 510',
  'pokemoneditor.iv': 'IW',
  'pokemoneditor.ivSetTo31': 'IWs auf 31 gesetzt',
  'pokemoneditor.perfectIvs': 'Perfekte IWs',
  'pokemoneditor.ivSetRandom': 'Zufällige IWs',
  'pokemoneditor.randomIvs': 'Zufällige IWs',
  'pokemoneditor.warnings': 'Warnungen',
  'pokemoneditor.warningsHint': 'Warnungen verhindern das Speichern nicht: Das Spiel akzeptiert das Pokémon trotzdem.',
  'generator.storageFull': 'Der Speicher ist voll (100 Pässe)',
  'generator.onlyRoomFor': 'Nur Platz für {count}: Diese werden erzeugt',
  'generator.generatedOne': '{count} Pass erzeugt',
  'generator.generatedMany': '{count} Pässe erzeugt',
  'generator.withSeed': '(Seed {seed})',
  'generator.allNamed': '· alle heißen „{name}“',
  'generator.willBeCalledOne': 'Er wird „{name}“ heißen',
  'generator.willBeCalledMany': 'Sie werden „{first}“, „{second}“… heißen',
  'generator.generateOne': '{count} Pass erzeugen',
  'generator.generateMany': '{count} Pässe erzeugen',
  'generator.howMany': 'Wie viele',
  'generator.passCount': 'Anzahl der Pässe',
  'generator.trainerName': 'Trainername',
  'generator.numberTokenHint': 'Schreibe {n} in den Namen, dort erscheint die Nummer jedes Passes: „random{n}“ ergibt random1, random2…',
  'generator.seed': 'Seed (optional)',
  'generator.seedPlaceholder': 'leer lassen für jedes Mal ein anderes Ergebnis',
  'generator.seedHint': 'Derselbe Seed erzeugt immer genau dieselben Pässe: nützlich, um sie zu teilen, ohne Dateien zu senden.',
  'generator.pokemon': 'Pokémon',
  'generator.moves': 'Attacken',
  'generator.moves.recommended': 'Empfohlen',
  'generator.moves.legalRandom': 'Legal, aber zufällig',
  'generator.moves.anything': 'Alles ist erlaubt',
  'generator.moves.hint': 'Immer 4 Attacken, und die Schaden verursachenden sind garantiert, außer in Fällen wie Ditto.',
  'generator.damaging': 'Schadensattacken',
  'generator.damaging.one': 'Mindestens eine',
  'generator.damaging.two': 'Mindestens zwei',
  'generator.damaging.hint': 'Mit zwei werden Kämpfe schneller entschieden; mit einer gibt es mehr Vielfalt und mehr Kuriositäten.',
  'generator.sameTypeMove': 'Mindestens eine Attacke des eigenen Typs',
  'generator.sameTypeMove.hint': 'Eine der vier gehört zu einem der Typen des Pokémon, unter den Schadensattacken, sofern vorhanden.',
  'generator.ivs': 'IWs',
  'generator.ivs.perfect': 'Alle auf 31',
  'generator.ivs.random': 'Zufällig',
  'generator.evs': 'EPs',
  'generator.evs.random': 'Zufällig',
  'generator.evs.even': 'Gleichmäßig (je 85)',
  'generator.ability': 'Fähigkeit',
  'generator.ability.legal': 'Eine der eigenen',
  'generator.ability.any': 'Beliebig',
  'generator.item': 'Item',
  'generator.item.none': 'Keins',
  'generator.item.random': 'Zufällig',
  'generator.evHint': 'EPs ergeben immer die vollen 510, mit höchstens 252 pro Statuswert.',
  'generator.rules': 'Regeln',
  'generator.atLeastOneLegendary': 'Mindestens ein Legendäres',
  'generator.atLeastOneLegendary.hint': 'Stellt sicher, dass eines der sechs legendär, halblegendär oder mystisch ist.',
  'generator.onlyFinalForms': 'Nur Endentwicklungen',
  'generator.onlyFinalForms.hint': 'Verwirft Stufen, die sich noch weiterentwickeln. Pokémon ohne Entwicklungslinie, wie Tauros, zählen weiterhin.',
  'generator.secret': 'Geheimer Modus',
  'generator.secret.hint': 'Du siehst die Pokémon nicht (es erscheint „?“) und kannst sie erst bearbeiten, nachdem der Pass auf die Wii übertragen wurde.',
  'generator.chaosName': 'Namens-Chaos',
  'generator.chaosName.hint': 'Derselbe Spitzname für alle Pokémon des Stapels, auch über verschiedene Pässe hinweg.',
  'generator.chaosNameText': 'Spitzname für alle',
  'generator.chaosNameText.placeholder': 'leer lassen für einen zufälligen',
  'generator.chaosNameText.hint': 'Leer: Beim Erzeugen wird ein zufälliges spanisches Wort aus einem Online-Wörterbuch angefragt. Da es von außen kommt, reproduziert der Seed dieses Wort nicht (offline wird eines aus der Reserveliste verwendet).',
  'generator.generating': 'Wird erzeugt…',
  'generator.preview': 'Vorschau',
  'generator.previewHint': 'Ein Beispiel mit den aktuellen Optionen:',
  'passeditor.phrase.greeting': 'Begrüßung',
  'passeditor.phrase.sentOut': 'Beim Einsetzen eines Pokémon',
  'passeditor.phrase.shift1': 'Wechsel 1',
  'passeditor.phrase.shift2': 'Wechsel 2',
  'passeditor.phrase.win': 'Beim Sieg',
  'passeditor.phrase.lose': 'Bei Niederlage',
  'passeditor.back': '‹ Pässe',
  'passeditor.secretMode': 'geheimer Modus',
  'passeditor.trainerName': 'Trainername',
  'passeditor.trainerModel': 'Trainer-Modell',
  'passeditor.trainerModelHint': 'Beim Wechsel des Charakters wird dessen Standardoutfit wiederhergestellt: Einzelne Kleidungsstücke lassen sich noch nicht auswählen.',
  'passeditor.selfIntroduction': 'Selbstvorstellung',
  'passeditor.currentDesign': 'Aktuelles Design: {design}. Das Design wird beim Übertragen auf die Wii gewählt, da es zum Speicherplatz gehört.',
  'passeditor.team': 'Team',
  'passeditor.secretBody': 'Dieser Pass ist im geheimen Modus: Er kann erst nach der Übertragung auf die Wii angesehen oder bearbeitet werden.',
  'passeditor.revealTitle': 'Pass aufdecken',
  'passeditor.revealBody': 'Der geheime Modus wird deaktiviert, und du kannst die Pokémon sehen und bearbeiten. Er lässt sich nicht erneut verbergen.',
  'passeditor.reveal': 'Aufdecken',
  'passeditor.revealed': 'Pass aufgedeckt',
  'passeditor.revealNow': 'Jetzt aufdecken',
  'passeditor.newPokemon': '+ Neu',
  'passeditor.fromOtherPass': '+ Aus anderem Pass',
  'passeditor.checksum': 'Prüfsumme',
  'passeditor.copyToOtherPass': 'In anderen Pass kopieren',
  'passeditor.removePokemonTitle': 'Pokémon entfernen',
  'passeditor.removePokemonBody': '{name} aus dem Pass entfernen?',
  'passeditor.remove': 'Entfernen',
  'passeditor.phrases': 'Sprüche',
  'passeditor.phrasesHint': 'Standardmäßig sagt der Trainer das, was zu seinem Charakter passt. Ein eigener Spruch ersetzt nur diesen einen.',
  'passeditor.presetPhrase': 'Standardspruch des Charakters',
  'passeditor.noPhrase': 'kein Spruch',
  'passeditor.resetToDefault': 'Auf Standard zurücksetzen',
  'passeditor.deletePassTitle': 'Pass löschen',
  'passeditor.deletePassBody': '„{name}“ aus dem lokalen Speicher löschen?',
  'passeditor.deletePass': 'Löschen',
  'passeditor.deleteThisPass': 'Diesen Pass löschen',
  'passlist.noPokemon': 'keine Pokémon',
  'passlist.deselect': 'Auswahl aufheben',
  'passlist.select': 'Auswählen',
  'passlist.selected': 'Ausgewählt',
  'passlist.notSelected': 'Nicht ausgewählt',
  'passlist.secret': 'geheim',
  'passlist.storageFull': 'Der Speicher ist voll (100 Pässe)',
  'passlist.secretPassesTitle': 'Pässe im geheimen Modus',
  'passlist.secretPassesBody': '{count} der Pässe sind im geheimen Modus. Nach dem Export kann jeder, der die Datei erhält, den Inhalt sehen. Fortfahren?',
  'passlist.exportAnyway': 'Trotzdem exportieren',
  'passlist.exportedOne': '{count} Pass exportiert',
  'passlist.exportedMany': '{count} Pässe exportiert',
  'passlist.deleteTitle': 'Pässe löschen',
  'passlist.deleteBodyOne': '{count} Pass wird aus dem lokalen Speicher gelöscht. Betrifft nichts auf der Wii.',
  'passlist.deleteBodyMany': '{count} Pässe werden aus dem lokalen Speicher gelöscht. Betrifft nichts auf der Wii.',
  'passlist.delete': 'Löschen',
  'passlist.deletedOne': '{count} Pass gelöscht',
  'passlist.deletedMany': '{count} Pässe gelöscht',
  'passlist.importPartial': 'Nur Platz für {saved} von {total}: Speicher ist voll (100 Pässe)',
  'passlist.importedOne': '{count} Pass importiert',
  'passlist.importedMany': '{count} Pässe importiert',
  'passlist.cannotReadFile': 'Die Datei konnte nicht gelesen werden',
  'passlist.storedPasses': 'gespeicherte Pässe',
  'passlist.import': 'Importieren',
  'passlist.newPass': 'Neuer Pass',
  'passlist.generate': 'Erzeugen',
  'passlist.emptyTitle': 'Noch keine Pässe gespeichert.',
  'passlist.emptyBody': 'Starte einen leeren Pass und stelle das Team selbst zusammen, erzeuge sie zufällig, importiere eine .aniapass-Datei oder lies die bereits auf der Wii vorhandenen ein.',
  'passlist.createPass': 'Pass erstellen',
  'passlist.generateRandom': 'Zufällig erzeugen',
  'passlist.nSelected': '{count} ausgewählt',
  'passlist.export': 'Exportieren',
  'copymon.empty': 'leer',
  'copymon.noTarget': 'Es gibt keinen anderen Pass, um es dorthin zu kopieren',
  'copymon.copyTitle': '{name} in einen anderen Pass kopieren',
  'copymon.copyHint': 'Es bleibt auch in diesem Pass: Es ist eine Kopie.',
  'copymon.copied': '{name} nach „{pass}“ kopiert',
  'copymon.noSource': 'Es gibt keinen anderen Pass mit Pokémon zum Übernehmen',
  'copymon.whichPass': 'Aus welchem Pass?',
  'copymon.whichPokemon': 'Pokémon aus „{pass}“',
  'copymon.bringHint': 'Es wird kopiert: Der andere Pass behält seins.',
};
