/** English — machine-drafted, lightly reviewed. */
export const en: Record<string, string> = {
  'state.noName': 'No name',
  'main.tab.passes': 'Passes',
  'main.tab.generate': 'Generate',
  'main.tab.wii': 'Wii',
  'main.editPass': 'Edit pass',
  'dom.accept': 'Accept',
  'dom.cancel': 'Cancel',
  'dom.nothingToPick': 'There is nothing to pick.',
  'dom.preparing': 'Preparing…',
  'dom.sizeOf': '{loaded} of {total}',
  'wii.phase.nand': 'The Wii is reading its save…',
  'wii.phase.data': 'Transferring…',
  'wii.phase.saving': 'The Wii is writing to the NAND. Do not turn it off.',
  'wii.sessionLost': 'The session with the Wii was lost',
  'wii.busyTitle': 'Another device holds the session',
  'wii.busyStale': 'It has been silent for {idle} s and expires on its own in {remaining} s. Usually it is a tab that was closed without the notice reaching the Wii: you can take it now.',
  'wii.busyActive': 'Another device is editing and is still active (last signal {idle} s ago). If nobody really is there, it will be free in {remaining} s.',
  'wii.takeover': 'Take over',
  'wii.contactLost': 'No contact with the Wii; retrying',
  'wii.contactBack': 'Contact with the Wii restored',
  'wii.releaseNote': 'Last close: {when} ({event}) — {what}',
  'wii.releaseSent': 'close notice sent to the Wii',
  'wii.releaseFallback': 'the browser refused the beacon; tried with fetch',
  'wii.releaseNothing': 'there was no session to release',
  'wii.enterAddress': "Enter the Wii's address",
  'wii.badAddress': "That address is not valid. Enter the Wii's IP or its name (for example, wii.local).",
  'wii.readingFromWii': "Reading the Wii's save",
  'wii.readFromWii': 'Save read from the Wii ({count} profiles)',
  'wii.cannotConnect': 'Could not connect',
  'wii.loaded': 'Save loaded: {count} profiles',
  'wii.notAPbrSave': 'The file is not a PBR save',
  'wii.savedLocally': '{count} passes saved locally',
  'wii.nothingSaved': 'Nothing was saved (full?)',
  'wii.selectInPassesTab': 'Select passes in the Passes tab',
  'wii.chooseNSlots': 'Choose {count} destination slots',
  'wii.overwriteTitle': 'You are about to overwrite passes',
  'wii.overwriteBody': '{count} of the chosen slots already have a pass: {names}. They will be lost.',
  'wii.overwrite': 'Overwrite',
  'wii.slotN': 'slot {n}',
  'wii.written': '{count} passes written to the save. Remember to send it to the Wii.',
  'wii.save': 'Save',
  'wii.loadHint': "Load the save from a file, or connect to the Wii assistant if it's running.",
  'wii.sameNetwork': 'This device has to be on the same local network as the Wii. A public IP with port forwarding will not work.',
  'wii.wiiAddress': "Wii's address",
  'wii.port': 'Port',
  'wii.connecting': 'Connecting…',
  'wii.connect': 'Connect to the Wii',
  'wii.openFile': 'Open file',
  'wii.source': 'source: {source}',
  'wii.editSessionOpen': 'edit session open',
  'wii.partition': 'partition {n}',
  'wii.saveNumber': 'save no. {n}',
  'wii.gameVersion': '{version} version · {lang}',
  'wii.version.jp': 'Japanese',
  'wii.version.int': 'international',
  'wii.profile': 'Profile',
  'wii.emptyFile': 'File {n} (empty)',
  'wii.close': 'Close',
  'wii.downloadBackup': 'Download original copy',
  'wii.queueTitle': 'Passes to be transferred',
  'wii.queueEmpty': 'None yet. Go to the Passes tab and mark the ones you want to send with the corner circle, or by long-pressing them.',
  'wii.noSlot': 'no slot',
  'wii.toSlot': '→ slot {n}',
  'wii.removeFromTransfer': 'Remove from transfer',
  'wii.markOneMoreSlot': 'Mark {count} more slot below: they are assigned in the order you tap them.',
  'wii.markNMoreSlots': 'Mark {count} more slots below: they are assigned in the order you tap them.',
  'wii.allSlotsPaired': 'Every pass already has its slot. Check the destinations before transferring.',
  'wii.passesInSave': 'Passes in the save ({used} of {total} personal)',
  'wii.design': 'design {n}',
  'wii.locked': 'locked',
  'wii.unused': 'unused',
  'wii.replaces': 'replaces {name}',
  'wii.theSlotN': 'slot {n}',
  'wii.actions': 'Actions',
  'wii.saveNLocally': 'Save {n} locally',
  'wii.transfer': 'Transfer',
  'wii.transferNToSlots': 'Transfer {n} to their slots',
  'wii.selectFirstHint': 'To transfer, first select passes in the Passes tab.',
  'wii.transferSummary': '{passes} · {slots} — {status}',
  'wii.nPassOne': '{n} pass',
  'wii.nPassMany': '{n} passes',
  'wii.nSlotOne': '{n} slot paired',
  'wii.nSlotMany': '{n} slots paired',
  'wii.missingOne': '{n} missing',
  'wii.missingMany': '{n} missing',
  'wii.allReady': 'all set',
  'wii.unlock': 'Unlocking',
  'wii.unlockHint': 'Pass slots and colosseums normally unlock by playing. This skips that.',
  'wii.unlockSlotsTitle': 'Unlock pass slots',
  'wii.unlockSlotsBody': "This profile's {n} personal pass slots will be marked as available.",
  'wii.unlock.button': 'Unlock',
  'wii.slotsUnlocked': 'Pass slots unlocked',
  'wii.allSlots': 'All slots',
  'wii.unlockColosseumsTitle': 'Unlock colosseums',
  'wii.unlockColosseumsBody': 'All ten colosseums will be marked as unlocked on this profile.',
  'wii.colosseumsUnlocked': 'Colosseums unlocked',
  'wii.allColosseums': 'All colosseums',
  'wii.send': 'Send',
  'wii.sendHint': 'Sending recalculates the checksums and increases the counter so the game prefers this save.',
  'wii.sessionOpenHint': 'While this screen stays open, no other device can edit the save. Press Close when done.',
  'wii.downloadSave': 'Download save',
  'wii.sendToWiiTitle': 'Send to the Wii',
  'wii.sendToWiiBody': "The Wii's save will be overwritten. Make sure you've downloaded the original copy first.",
  'wii.send.button': 'Send',
  'wii.noSession': 'There is no open session with the Wii',
  'wii.sendingToWii': 'Sending the save to the Wii',
  'wii.sentToWii': 'Save sent to the Wii',
  'wii.cannotSend': 'Could not send',
  'wii.sendToWii': 'Send to the Wii',
  'pokemoneditor.stat.hp': 'HP',
  'pokemoneditor.stat.atk': 'Atk',
  'pokemoneditor.stat.def': 'Def',
  'pokemoneditor.stat.spa': 'SpA',
  'pokemoneditor.stat.spd': 'SpD',
  'pokemoneditor.stat.spe': 'Spe',
  'pokemoneditor.noItem': '— none —',
  'pokemoneditor.male': 'Male',
  'pokemoneditor.female': 'Female',
  'pokemoneditor.back': '‹ Back',
  'pokemoneditor.noPidForGender': 'No PID of that gender was found for this Pokémon',
  'pokemoneditor.level': 'Lv. {level}',
  'pokemoneditor.shinyBadge': 'shiny',
  'pokemoneditor.shinyLabel': 'Shiny',
  'pokemoneditor.species': 'Species',
  'pokemoneditor.nickname': 'Nickname',
  'pokemoneditor.own': 'own',
  'pokemoneditor.nature': 'Nature',
  'pokemoneditor.noPidForNature': 'No PID with that nature was found for this Pokémon',
  'pokemoneditor.ability': 'Ability',
  'pokemoneditor.item': 'Item',
  'pokemoneditor.pidNotHex': 'The PID is 8 hexadecimal digits',
  'pokemoneditor.random': 'Random',
  'pokemoneditor.pidHint': 'It determines the nature, the gender and which ability the game uses.',
  'pokemoneditor.abilityMismatch': '⚠ The PID\'s low bit calls for {ability}. The game respects the saved ability, but a legality checker would flag it.',
  'pokemoneditor.moves': 'Moves',
  'pokemoneditor.recommended': 'Recommended',
  'pokemoneditor.recommendedHint': 'the ones the game would give it at level 50',
  'pokemoneditor.emptySlot': '— empty —',
  'pokemoneditor.allowIllegal': 'Allow illegal moves',
  'pokemoneditor.noDamagingMove': 'No move deals damage.',
  'pokemoneditor.stats': 'Stats',
  'pokemoneditor.statsHint': 'EVs are distributed (510 total). IVs are fixed at birth: 31 is the maximum.',
  'pokemoneditor.ev': 'EV',
  'pokemoneditor.evOf510': 'EV: {total} / 510',
  'pokemoneditor.iv': 'IV',
  'pokemoneditor.ivSetTo31': 'IVs set to 31',
  'pokemoneditor.perfectIvs': 'Perfect IVs',
  'pokemoneditor.ivSetRandom': 'Random IVs',
  'pokemoneditor.randomIvs': 'Random IVs',
  'pokemoneditor.warnings': 'Warnings',
  'pokemoneditor.warningsHint': 'Warnings do not prevent saving: the game will accept the Pokémon anyway.',
  'generator.storageFull': 'Storage is full (100 passes)',
  'generator.onlyRoomFor': 'Only room for {count}: those are the ones that will be generated',
  'generator.generatedOne': '{count} pass generated',
  'generator.generatedMany': '{count} passes generated',
  'generator.withSeed': '(seed {seed})',
  'generator.allNamed': '· all named "{name}"',
  'generator.willBeCalledOne': 'It will be called "{name}"',
  'generator.willBeCalledMany': 'They will be called "{first}", "{second}"…',
  'generator.generateOne': 'Generate {count} pass',
  'generator.generateMany': 'Generate {count} passes',
  'generator.howMany': 'How many',
  'generator.passCount': 'Number of passes',
  'generator.trainerName': 'Trainer name',
  'generator.numberTokenHint': 'Type {n} in the name and each pass\'s number will go there: "random{n}" gives random1, random2…',
  'generator.seed': 'Seed (optional)',
  'generator.seedPlaceholder': 'leave it empty for a different one each time',
  'generator.seedHint': 'The same seed always produces exactly the same passes: useful for sharing them without sending files.',
  'generator.pokemon': 'Pokémon',
  'generator.moves': 'Moves',
  'generator.moves.recommended': 'Recommended',
  'generator.moves.legalRandom': 'Legal, but random',
  'generator.moves.anything': 'Anything goes',
  'generator.moves.hint': 'Always 4 moves, and the damaging ones are guaranteed except in cases like Ditto.',
  'generator.damaging': 'Damaging moves',
  'generator.damaging.one': 'At least one',
  'generator.damaging.two': 'At least two',
  'generator.damaging.hint': 'With two, battles are decided sooner; with one there is more variety and more oddities.',
  'generator.sameTypeMove': 'At least one same-type move',
  'generator.sameTypeMove.hint': 'One of the four will be of one of the Pokémon\'s types, and among the damaging ones whenever one exists.',
  'generator.ivs': 'IVs',
  'generator.ivs.perfect': 'All at 31',
  'generator.ivs.random': 'Random',
  'generator.evs': 'EVs',
  'generator.evs.random': 'Random',
  'generator.evs.even': 'Even (85 each)',
  'generator.ability': 'Ability',
  'generator.ability.legal': 'One of its own',
  'generator.ability.any': 'Any',
  'generator.item': 'Item',
  'generator.item.none': 'None',
  'generator.item.random': 'Random',
  'generator.evHint': 'EVs always add up to the full 510, with a maximum of 252 per stat.',
  'generator.rules': 'Rules',
  'generator.atLeastOneLegendary': 'At least one legendary',
  'generator.atLeastOneLegendary.hint': 'Guarantees one of the six is legendary, sub-legendary or mythical.',
  'generator.onlyFinalForms': 'Only final forms',
  'generator.onlyFinalForms.hint': 'Discards stages that still evolve. Pokémon without an evolution line, like Tauros, still count.',
  'generator.secret': 'Secret mode',
  'generator.secret.hint': 'You will not see the Pokémon (it will show "?") nor be able to edit them until the pass is transferred to the Wii.',
  'generator.chaosName': 'Nickname chaos',
  'generator.chaosName.hint': 'The same nickname for every Pokémon in the batch, even across different passes.',
  'generator.chaosNameText': 'Everyone\'s nickname',
  'generator.chaosNameText.placeholder': 'leave it empty for a random one',
  'generator.chaosNameText.hint': 'Empty: a random Spanish word is requested from an online dictionary when generating. Since it comes from outside, the seed does not reproduce that word (offline, one from the backup list is used).',
  'generator.generating': 'Generating…',
  'generator.preview': 'Preview',
  'generator.previewHint': 'An example with the current options:',
  'passeditor.phrase.greeting': 'Greeting',
  'passeditor.phrase.sentOut': 'Sending out a Pokémon',
  'passeditor.phrase.shift1': 'Switch 1',
  'passeditor.phrase.shift2': 'Switch 2',
  'passeditor.phrase.win': 'On winning',
  'passeditor.phrase.lose': 'On losing',
  'passeditor.back': '‹ Passes',
  'passeditor.secretMode': 'secret mode',
  'passeditor.trainerName': 'Trainer name',
  'passeditor.trainerModel': 'Trainer model',
  'passeditor.trainerModelHint': 'Switching characters resets their default outfit: there is no way yet to pick each garment individually.',
  'passeditor.selfIntroduction': 'Self-introduction',
  'passeditor.currentDesign': 'Current design: {design}. The design is chosen when transferring to the Wii, because it belongs to the save slot.',
  'passeditor.team': 'Team',
  'passeditor.secretBody': 'This pass is in secret mode: it cannot be seen or edited until it is transferred to the Wii.',
  'passeditor.revealTitle': 'Reveal the pass',
  'passeditor.revealBody': 'Secret mode will be turned off and you will be able to see and edit the Pokémon. It cannot be hidden again.',
  'passeditor.reveal': 'Reveal',
  'passeditor.revealed': 'Pass revealed',
  'passeditor.revealNow': 'Reveal now',
  'passeditor.newPokemon': '+ New',
  'passeditor.fromOtherPass': '+ From another pass',
  'passeditor.checksum': 'checksum',
  'passeditor.copyToOtherPass': 'Copy to another pass',
  'passeditor.removePokemonTitle': 'Remove Pokémon',
  'passeditor.removePokemonBody': 'Remove {name} from the pass?',
  'passeditor.remove': 'Remove',
  'passeditor.phrases': 'Phrases',
  'passeditor.phrasesHint': 'By default, the trainer says whatever fits their character. Writing your own phrase only replaces that one.',
  'passeditor.presetPhrase': "character's default phrase",
  'passeditor.noPhrase': 'no phrase',
  'passeditor.resetToDefault': 'Reset to default',
  'passeditor.deletePassTitle': 'Delete pass',
  'passeditor.deletePassBody': 'Delete "{name}" from local storage?',
  'passeditor.deletePass': 'Delete',
  'passeditor.deleteThisPass': 'Delete this pass',
  'passlist.noPokemon': 'no Pokémon',
  'passlist.deselect': 'Remove from selection',
  'passlist.select': 'Select',
  'passlist.selected': 'Selected',
  'passlist.notSelected': 'Not selected',
  'passlist.secret': 'secret',
  'passlist.storageFull': 'Storage is full (100 passes)',
  'passlist.secretPassesTitle': 'Passes in secret mode',
  'passlist.secretPassesBody': '{count} of the passes are in secret mode. Once exported, whoever receives the file will be able to see their content. Continue?',
  'passlist.exportAnyway': 'Export anyway',
  'passlist.exportedOne': '{count} pass exported',
  'passlist.exportedMany': '{count} passes exported',
  'passlist.deleteTitle': 'Delete passes',
  'passlist.deleteBodyOne': '{count} pass will be deleted from local storage. It does not affect anything on the Wii.',
  'passlist.deleteBodyMany': '{count} passes will be deleted from local storage. It does not affect anything on the Wii.',
  'passlist.delete': 'Delete',
  'passlist.deletedOne': '{count} pass deleted',
  'passlist.deletedMany': '{count} passes deleted',
  'passlist.importPartial': 'Only room for {saved} of {total}: storage is full (100 passes)',
  'passlist.importedOne': '{count} pass imported',
  'passlist.importedMany': '{count} passes imported',
  'passlist.cannotReadFile': 'The file could not be read',
  'passlist.storedPasses': 'stored passes',
  'passlist.import': 'Import',
  'passlist.newPass': 'New pass',
  'passlist.generate': 'Generate',
  'passlist.emptyTitle': 'No passes stored yet.',
  'passlist.emptyBody': 'Start a blank pass and build the team yourself, generate them at random, import a .aniapass file, or read the ones already on the Wii.',
  'passlist.createPass': 'Create a pass',
  'passlist.generateRandom': 'Generate at random',
  'passlist.nSelected': '{count} selected',
  'passlist.export': 'Export',
  'copymon.empty': 'empty',
  'copymon.noTarget': 'There is no other pass to copy it to',
  'copymon.copyTitle': 'Copy {name} to another pass',
  'copymon.copyHint': 'It also stays in this pass: it is a copy.',
  'copymon.copied': '{name} copied to "{pass}"',
  'copymon.noSource': 'There is no other pass with Pokémon to bring in',
  'copymon.whichPass': 'From which pass?',
  'copymon.whichPokemon': 'Pokémon from "{pass}"',
  'copymon.bringHint': 'It gets copied: the other pass keeps its own.',
};
