/** Español — idioma de referencia. Claves con prefijo por fichero de origen. */
export const es: Record<string, string> = {
  'state.noName': 'Sin nombre',
  'main.tab.passes': 'Pases',
  'main.tab.generate': 'Generar',
  'main.tab.wii': 'Wii',
  'main.editPass': 'Editar pase',
  'dom.accept': 'Aceptar',
  'dom.cancel': 'Cancelar',
  'dom.nothingToPick': 'No hay nada que elegir.',
  'dom.preparing': 'Preparando…',
  'dom.sizeOf': '{loaded} de {total}',
  'wii.phase.nand': 'La Wii está leyendo su guardado…',
  'wii.phase.data': 'Transfiriendo…',
  'wii.phase.saving': 'La Wii está escribiendo en la NAND. No la apagues.',
  'wii.sessionLost': 'Se ha perdido la sesión con la Wii',
  'wii.busyTitle': 'La sesión la tiene otro dispositivo',
  'wii.busyStale': 'Lleva {idle} s sin dar señales y caduca sola en {remaining} s. Casi siempre es una pestaña que se cerró sin que el aviso llegara a la Wii: puedes quedártela ahora.',
  'wii.busyActive': 'Otro dispositivo está editando y sigue activo (última señal hace {idle} s). Si de verdad no hay nadie, quedará libre en {remaining} s.',
  'wii.takeover': 'Tomar el relevo',
  'wii.contactLost': 'Sin contacto con la Wii; reintentando',
  'wii.contactBack': 'Contacto con la Wii recuperado',
  'wii.releaseNote': 'Último cierre: {when} ({event}) — {what}',
  'wii.releaseSent': 'aviso de cierre enviado a la Wii',
  'wii.releaseFallback': 'el navegador no lo mandó como beacon; se intentó con fetch',
  'wii.releaseNothing': 'no había sesión que soltar',
  'wii.enterAddress': 'Escribe la dirección de la Wii',
  'wii.badAddress': 'Esa dirección no vale. Escribe la IP de la Wii o su nombre (por ejemplo, wii.local).',
  'wii.readingFromWii': 'Leyendo el guardado de la Wii',
  'wii.readFromWii': 'Guardado leído de la Wii ({count} perfiles)',
  'wii.cannotConnect': 'No se ha podido conectar',
  'wii.loaded': 'Guardado cargado: {count} perfiles',
  'wii.notAPbrSave': 'El fichero no es un guardado de PBR',
  'wii.savedLocally': '{count} pases guardados en local',
  'wii.nothingSaved': 'No se ha guardado nada (¿lleno?)',
  'wii.selectInPassesTab': 'Selecciona pases en la pestaña Pases',
  'wii.chooseNSlots': 'Elige {count} ranuras de destino',
  'wii.overwriteTitle': 'Vas a sobrescribir pases',
  'wii.overwriteBody': '{count} de las ranuras elegidas ya tienen un pase: {names}. Se perderán.',
  'wii.overwrite': 'Sobrescribir',
  'wii.slotN': 'ranura {n}',
  'wii.written': '{count} pases escritos en el guardado. Recuerda enviarlo a la Wii.',
  'wii.save': 'Guardado',
  'wii.loadHint': 'Carga el guardado desde un fichero, o conéctate al asistente Wii si lo tienes en marcha.',
  'wii.sameNetwork': 'Este dispositivo tiene que estar en la misma red local que la Wii. Una IP pública con redirección de puertos no sirve.',
  'wii.wiiAddress': 'Dirección de la Wii',
  'wii.port': 'Puerto',
  'wii.connecting': 'Conectando…',
  'wii.connect': 'Conectar con la Wii',
  'wii.openFile': 'Abrir fichero',
  'wii.source': 'origen: {source}',
  'wii.editSessionOpen': 'sesión de edición abierta',
  'wii.partition': 'partición {n}',
  'wii.saveNumber': 'guardado nº {n}',
  'wii.gameVersion': 'versión {version} · {lang}',
  'wii.version.jp': 'japonesa',
  'wii.version.int': 'internacional',
  'wii.profile': 'Perfil',
  'wii.emptyFile': 'Archivo {n} (vacío)',
  'wii.close': 'Cerrar',
  'wii.downloadBackup': 'Descargar copia original',
  'wii.queueTitle': 'Pases que se van a transferir',
  'wii.queueEmpty': 'Ninguno todavía. Ve a la pestaña Pases y marca los que quieras enviar con el redondel de su esquina, o manteniéndolos pulsados.',
  'wii.noSlot': 'sin ranura',
  'wii.toSlot': '→ ranura {n}',
  'wii.removeFromTransfer': 'Quitar de la transferencia',
  'wii.markOneMoreSlot': 'Marca {count} ranura más abajo: se reparten en el orden en que las toques.',
  'wii.markNMoreSlots': 'Marca {count} ranuras más abajo: se reparten en el orden en que las toques.',
  'wii.allSlotsPaired': 'Cada pase tiene ya su ranura. Comprueba los destinos antes de transferir.',
  'wii.passesInSave': 'Pases en el guardado ({used} de {total} personales)',
  'wii.design': 'diseño {n}',
  'wii.locked': 'bloqueado',
  'wii.unused': 'sin usar',
  'wii.replaces': 'sustituye a {name}',
  'wii.theSlotN': 'la ranura {n}',
  'wii.actions': 'Acciones',
  'wii.saveNLocally': 'Guardar {n} en local',
  'wii.transfer': 'Transferir',
  'wii.transferNToSlots': 'Transferir {n} a sus ranuras',
  'wii.selectFirstHint': 'Para transferir, selecciona antes los pases en la pestaña Pases.',
  'wii.transferSummary': '{passes} · {slots} — {status}',
  'wii.nPassOne': '{n} pase',
  'wii.nPassMany': '{n} pases',
  'wii.nSlotOne': '{n} ranura emparejada',
  'wii.nSlotMany': '{n} ranuras emparejadas',
  'wii.missingOne': 'falta {n}',
  'wii.missingMany': 'faltan {n}',
  'wii.allReady': 'todo listo',
  'wii.unlock': 'Desbloqueo',
  'wii.unlockHint': 'Normalmente las ranuras de pase y los coliseos se desbloquean jugando. Esto lo salta.',
  'wii.unlockSlotsTitle': 'Desbloquear ranuras de pase',
  'wii.unlockSlotsBody': 'Se marcarán como disponibles las {n} ranuras de pase personal de este perfil.',
  'wii.unlock.button': 'Desbloquear',
  'wii.slotsUnlocked': 'Ranuras de pase desbloqueadas',
  'wii.allSlots': 'Todas las ranuras',
  'wii.unlockColosseumsTitle': 'Desbloquear coliseos',
  'wii.unlockColosseumsBody': 'Se marcarán los diez coliseos como desbloqueados en este perfil.',
  'wii.colosseumsUnlocked': 'Coliseos desbloqueados',
  'wii.allColosseums': 'Todos los coliseos',
  'wii.send': 'Enviar',
  'wii.sendHint': 'Al enviar se recalculan los checksums y se incrementa el contador para que el juego prefiera esta partida.',
  'wii.sessionOpenHint': 'Mientras esta pantalla siga abierta, ningún otro dispositivo puede editar el guardado. Pulsa Cerrar al terminar.',
  'wii.downloadSave': 'Descargar guardado',
  'wii.sendToWiiTitle': 'Enviar a la Wii',
  'wii.sendToWiiBody': 'Se sobrescribirá el guardado de la Wii. Asegúrate de haber descargado la copia original antes.',
  'wii.send.button': 'Enviar',
  'wii.noSession': 'No hay sesión abierta con la Wii',
  'wii.sendingToWii': 'Enviando el guardado a la Wii',
  'wii.sentToWii': 'Guardado enviado a la Wii',
  'wii.cannotSend': 'No se ha podido enviar',
  'wii.sendToWii': 'Enviar a la Wii',
  'pokemoneditor.stat.hp': 'PS',
  'pokemoneditor.stat.atk': 'At',
  'pokemoneditor.stat.def': 'Def',
  'pokemoneditor.stat.spa': 'AtEs',
  'pokemoneditor.stat.spd': 'DefEs',
  'pokemoneditor.stat.spe': 'Vel',
  'pokemoneditor.noItem': '— ninguno —',
  'pokemoneditor.male': 'Macho',
  'pokemoneditor.female': 'Hembra',
  'pokemoneditor.back': '‹ Volver',
  'pokemoneditor.noPidForGender': 'No se ha encontrado un PID de ese género para este Pokémon',
  'pokemoneditor.level': 'Nv. {level}',
  'pokemoneditor.shinyBadge': 'variocolor',
  'pokemoneditor.shinyLabel': 'Variocolor',
  'pokemoneditor.species': 'Especie',
  'pokemoneditor.nickname': 'Mote',
  'pokemoneditor.own': 'propio',
  'pokemoneditor.nature': 'Naturaleza',
  'pokemoneditor.noPidForNature': 'No se ha encontrado un PID con esa naturaleza para este Pokémon',
  'pokemoneditor.ability': 'Habilidad',
  'pokemoneditor.item': 'Objeto',
  'pokemoneditor.pidNotHex': 'El PID son 8 dígitos hexadecimales',
  'pokemoneditor.random': 'Al azar',
  'pokemoneditor.pidHint': 'De él salen la naturaleza, el género y qué habilidad usa el juego.',
  'pokemoneditor.abilityMismatch': '⚠ El bit bajo del PID pide {ability}. El juego respeta la habilidad guardada, pero un comprobador de legalidad lo marcaría.',
  'pokemoneditor.moves': 'Movimientos',
  'pokemoneditor.recommended': 'Recomendados',
  'pokemoneditor.recommendedHint': 'los que le pondría el juego a nivel 50',
  'pokemoneditor.emptySlot': '— vacío —',
  'pokemoneditor.allowIllegal': 'Permitir movimientos ilegales',
  'pokemoneditor.noDamagingMove': 'Ningún movimiento hace daño.',
  'pokemoneditor.stats': 'Estadísticas',
  'pokemoneditor.statsHint': 'Los EV se reparten (510 en total). Los IV son fijos de nacimiento: 31 es el máximo.',
  'pokemoneditor.ev': 'EV',
  'pokemoneditor.evOf510': 'EV: {total} / 510',
  'pokemoneditor.iv': 'IV',
  'pokemoneditor.ivSetTo31': 'IV puestos a 31',
  'pokemoneditor.perfectIvs': 'IV perfectos',
  'pokemoneditor.ivSetRandom': 'IV al azar',
  'pokemoneditor.randomIvs': 'IV al azar',
  'pokemoneditor.warnings': 'Advertencias',
  'pokemoneditor.warningsHint': 'Las advertencias no impiden guardar: el juego aceptará el Pokémon igualmente.',
  'generator.storageFull': 'El almacenamiento está lleno (100 pases)',
  'generator.onlyRoomFor': 'Solo caben {count}: se generarán esos',
  'generator.generatedOne': '{count} pase generado',
  'generator.generatedMany': '{count} pases generados',
  'generator.withSeed': '(semilla {seed})',
  'generator.allNamed': '· todos se llaman «{name}»',
  'generator.willBeCalledOne': 'Se llamará «{name}»',
  'generator.willBeCalledMany': 'Se llamarán «{first}», «{second}»…',
  'generator.generateOne': 'Generar {count} pase',
  'generator.generateMany': 'Generar {count} pases',
  'generator.howMany': 'Cuántos',
  'generator.passCount': 'Número de pases',
  'generator.trainerName': 'Nombre del entrenador',
  'generator.numberTokenHint': 'Escribe {n} en el nombre y ahí irá el número de cada pase: «random{n}» da random1, random2…',
  'generator.seed': 'Semilla (opcional)',
  'generator.seedPlaceholder': 'déjalo vacío para que sea distinto cada vez',
  'generator.seedHint': 'Con la misma semilla salen exactamente los mismos pases: sirve para compartirlos sin mandar ficheros.',
  'generator.pokemon': 'Pokémon',
  'generator.moves': 'Movimientos',
  'generator.moves.recommended': 'Recomendados',
  'generator.moves.legalRandom': 'Legales, pero al azar',
  'generator.moves.anything': 'Todo vale',
  'generator.moves.hint': 'Siempre 4 movimientos, y los que hagan daño se garantizan salvo en casos como Ditto.',
  'generator.damaging': 'Movimientos que hagan daño',
  'generator.damaging.one': 'Al menos uno',
  'generator.damaging.two': 'Al menos dos',
  'generator.damaging.hint': 'Con dos, los combates se resuelven antes; con uno hay más variedad y más rarezas.',
  'generator.sameTypeMove': 'Al menos un movimiento de su tipo',
  'generator.sameTypeMove.hint': 'Uno de los cuatro será de uno de los tipos del Pokémon, y de los que hacen daño siempre que exista.',
  'generator.ivs': 'IV',
  'generator.ivs.perfect': 'Todos a 31',
  'generator.ivs.random': 'Aleatorios',
  'generator.evs': 'EV',
  'generator.evs.random': 'Aleatorios',
  'generator.evs.even': 'Repartidos (85 en cada una)',
  'generator.ability': 'Habilidad',
  'generator.ability.legal': 'Una de las suyas',
  'generator.ability.any': 'Cualquiera',
  'generator.item': 'Objeto',
  'generator.item.none': 'Ninguno',
  'generator.item.random': 'Aleatorio',
  'generator.evHint': 'Los EV siempre suman los 510 completos, con un máximo de 252 por estadística.',
  'generator.rules': 'Reglas',
  'generator.atLeastOneLegendary': 'Al menos un legendario',
  'generator.atLeastOneLegendary.hint': 'Garantiza que uno de los seis sea legendario, sublegendario o mítico.',
  'generator.onlyFinalForms': 'Solo formas finales',
  'generator.onlyFinalForms.hint': 'Descarta las fases que aún evolucionan. Los Pokémon sin línea evolutiva, como Tauros, siguen entrando.',
  'generator.secret': 'Modo secreto',
  'generator.secret.hint': 'No verás los Pokémon (saldrá "?") ni podrás editarlos hasta transferir el pase a la Wii.',
  'generator.chaosName': 'Caos de nombre',
  'generator.chaosName.hint': 'Un mismo mote para todos los Pokémon del lote, incluso los de pases distintos.',
  'generator.chaosNameText': 'El mote de todos',
  'generator.chaosNameText.placeholder': 'déjalo vacío y sale al azar',
  'generator.chaosNameText.hint': 'Vacío: al generar se pide una palabra española al azar a un diccionario de internet. Como viene de fuera, esa palabra no la reproduce la semilla (sin conexión sale una de la lista de reserva).',
  'generator.generating': 'Generando…',
  'generator.preview': 'Vista previa',
  'generator.previewHint': 'Un ejemplo con las opciones actuales:',
  'passeditor.phrase.greeting': 'Saludo',
  'passeditor.phrase.sentOut': 'Al sacar un Pokémon',
  'passeditor.phrase.shift1': 'Cambio 1',
  'passeditor.phrase.shift2': 'Cambio 2',
  'passeditor.phrase.win': 'Al ganar',
  'passeditor.phrase.lose': 'Al perder',
  'passeditor.back': '‹ Pases',
  'passeditor.secretMode': 'modo secreto',
  'passeditor.trainerName': 'Nombre del entrenador',
  'passeditor.trainerModel': 'Modelo del entrenador',
  'passeditor.trainerModelHint': 'Al cambiar de personaje se repone su vestuario de fábrica: no hay forma de elegir prenda a prenda todavía.',
  'passeditor.selfIntroduction': 'Autopresentación',
  'passeditor.currentDesign': 'Diseño actual: {design}. El diseño se elige al transferir a la Wii, porque pertenece a la ranura del guardado.',
  'passeditor.team': 'Equipo',
  'passeditor.secretBody': 'Este pase está en modo secreto: no se puede ver ni editar hasta transferirlo a la Wii.',
  'passeditor.revealTitle': 'Revelar el pase',
  'passeditor.revealBody': 'Se desactivará el modo secreto y podrás ver y editar los Pokémon. No se puede volver a ocultar.',
  'passeditor.reveal': 'Revelar',
  'passeditor.revealed': 'Pase revelado',
  'passeditor.revealNow': 'Revelar ahora',
  'passeditor.newPokemon': '+ Nuevo',
  'passeditor.fromOtherPass': '+ De otro pase',
  'passeditor.checksum': 'checksum',
  'passeditor.copyToOtherPass': 'Copiar a otro pase',
  'passeditor.removePokemonTitle': 'Quitar Pokémon',
  'passeditor.removePokemonBody': '¿Quitar a {name} del pase?',
  'passeditor.remove': 'Quitar',
  'passeditor.phrases': 'Frases',
  'passeditor.phrasesHint': 'De fábrica, el entrenador dice lo que le corresponde a su personaje. Al escribir una frase propia se sustituye solo esa.',
  'passeditor.presetPhrase': 'frase de fábrica del personaje',
  'passeditor.noPhrase': 'sin frase',
  'passeditor.resetToDefault': 'Volver a la de fábrica',
  'passeditor.deletePassTitle': 'Borrar pase',
  'passeditor.deletePassBody': '¿Borrar "{name}" del almacenamiento local?',
  'passeditor.deletePass': 'Borrar',
  'passeditor.deleteThisPass': 'Borrar este pase',
  'passlist.noPokemon': 'sin Pokémon',
  'passlist.deselect': 'Quitar de la selección',
  'passlist.select': 'Seleccionar',
  'passlist.selected': 'Seleccionado',
  'passlist.notSelected': 'Sin seleccionar',
  'passlist.secret': 'secreto',
  'passlist.storageFull': 'El almacenamiento está lleno (100 pases)',
  'passlist.secretPassesTitle': 'Pases en modo secreto',
  'passlist.secretPassesBody': '{count} de los pases están en modo secreto. Al exportarlos, quien reciba el fichero podrá ver su contenido. ¿Seguir?',
  'passlist.exportAnyway': 'Exportar igualmente',
  'passlist.exportedOne': '{count} pase exportado',
  'passlist.exportedMany': '{count} pases exportados',
  'passlist.deleteTitle': 'Borrar pases',
  'passlist.deleteBodyOne': 'Se va a borrar {count} pase del almacenamiento local. No afecta a lo que haya en la Wii.',
  'passlist.deleteBodyMany': 'Se van a borrar {count} pases del almacenamiento local. No afecta a lo que haya en la Wii.',
  'passlist.delete': 'Borrar',
  'passlist.deletedOne': '{count} pase borrado',
  'passlist.deletedMany': '{count} pases borrados',
  'passlist.importPartial': 'Solo caben {saved} de {total}: el almacenamiento está lleno (100 pases)',
  'passlist.importedOne': '{count} pase importado',
  'passlist.importedMany': '{count} pases importados',
  'passlist.cannotReadFile': 'No se ha podido leer el fichero',
  'passlist.storedPasses': 'pases guardados',
  'passlist.import': 'Importar',
  'passlist.newPass': 'Pase nuevo',
  'passlist.generate': 'Generar',
  'passlist.emptyTitle': 'Todavía no hay pases guardados.',
  'passlist.emptyBody': 'Empieza un pase en blanco y monta el equipo tú, genéralos al azar, importa un fichero .aniapass o lee los que ya tengas en la Wii.',
  'passlist.createPass': 'Crear un pase',
  'passlist.generateRandom': 'Generar al azar',
  'passlist.nSelected': '{count} seleccionados',
  'passlist.export': 'Exportar',
  'copymon.empty': 'vacío',
  'copymon.noTarget': 'No hay otro pase donde copiarlo',
  'copymon.copyTitle': 'Copiar a {name} a otro pase',
  'copymon.copyHint': 'Se queda también en este pase: es una copia.',
  'copymon.copied': '{name} copiado a «{pass}»',
  'copymon.noSource': 'No hay otro pase con Pokémon que traer',
  'copymon.whichPass': '¿De qué pase?',
  'copymon.whichPokemon': 'Pokémon de «{pass}»',
  'copymon.bringHint': 'Se copia: el otro pase se queda con el suyo.',
};
