/** Français — traduction automatique, revue superficielle uniquement. */
export const fr: Record<string, string> = {
  'state.noName': 'Sans nom',
  'main.tab.passes': 'Pass',
  'main.tab.generate': 'Générer',
  'main.tab.wii': 'Wii',
  'main.editPass': 'Modifier le pass',
  'dom.accept': 'Accepter',
  'dom.cancel': 'Annuler',
  'dom.nothingToPick': "Il n'y a rien à choisir.",
  'dom.preparing': 'Préparation…',
  'dom.sizeOf': '{loaded} sur {total}',
  'wii.phase.nand': 'La Wii lit sa sauvegarde…',
  'wii.phase.data': 'Transfert en cours…',
  'wii.phase.saving': "La Wii écrit sur la mémoire NAND. Ne l'éteins pas.",
  'wii.sessionLost': 'La session avec la Wii a été perdue',
  'wii.busyTitle': 'Un autre appareil détient la session',
  'wii.busyStale': 'Silencieuse depuis {idle} s, elle expirera seule dans {remaining} s. C’est presque toujours un onglet fermé dont l’avis n’est pas arrivé à la Wii : tu peux la reprendre.',
  'wii.busyActive': 'Un autre appareil édite et reste actif (dernier signal il y a {idle} s). Si personne n’est vraiment là, elle se libérera dans {remaining} s.',
  'wii.takeover': 'Reprendre la session',
  'wii.contactLost': 'Plus de contact avec la Wii ; nouvel essai',
  'wii.contactBack': 'Contact avec la Wii rétabli',
  'wii.releaseNote': 'Dernière fermeture : {when} ({event}) — {what}',
  'wii.releaseSent': 'avis de fermeture envoyé à la Wii',
  'wii.releaseFallback': 'le navigateur a refusé le beacon ; tenté avec fetch',
  'wii.releaseNothing': 'il n’y avait pas de session à libérer',
  'wii.enterAddress': "Saisis l'adresse de la Wii",
  'wii.badAddress': "Cette adresse n'est pas valide. Saisis l'IP de la Wii ou son nom (par exemple wii.local).",
  'wii.readingFromWii': 'Lecture de la sauvegarde de la Wii',
  'wii.readFromWii': 'Sauvegarde lue depuis la Wii ({count} profils)',
  'wii.cannotConnect': 'Connexion impossible',
  'wii.loaded': 'Sauvegarde chargée : {count} profils',
  'wii.notAPbrSave': "Le fichier n'est pas une sauvegarde PBR",
  'wii.savedLocally': '{count} pass enregistrés en local',
  'wii.nothingSaved': "Rien n'a été enregistré (plein ?)",
  'wii.selectInPassesTab': "Sélectionne des pass dans l'onglet Pass",
  'wii.chooseNSlots': 'Choisis {count} emplacements de destination',
  'wii.overwriteTitle': 'Tu vas écraser des pass',
  'wii.overwriteBody': '{count} des emplacements choisis ont déjà un pass : {names}. Ils seront perdus.',
  'wii.overwrite': 'Écraser',
  'wii.slotN': 'emplacement {n}',
  'wii.written': '{count} pass écrits dans la sauvegarde. Pense à l\'envoyer à la Wii.',
  'wii.save': 'Sauvegarde',
  'wii.loadHint': "Charge la sauvegarde depuis un fichier, ou connecte-toi à l'assistant Wii s'il est lancé.",
  'wii.sameNetwork': "Cet appareil doit être sur le même réseau local que la Wii. Une IP publique avec redirection de ports ne marche pas.",
  'wii.wiiAddress': 'Adresse de la Wii',
  'wii.port': 'Port',
  'wii.connecting': 'Connexion…',
  'wii.connect': 'Se connecter à la Wii',
  'wii.openFile': 'Ouvrir un fichier',
  'wii.source': 'source : {source}',
  'wii.editSessionOpen': "session d'édition ouverte",
  'wii.partition': 'partition {n}',
  'wii.saveNumber': 'sauvegarde n° {n}',
  'wii.gameVersion': 'version {version} · {lang}',
  'wii.version.jp': 'japonaise',
  'wii.version.int': 'internationale',
  'wii.profile': 'Profil',
  'wii.emptyFile': 'Fichier {n} (vide)',
  'wii.close': 'Fermer',
  'wii.downloadBackup': 'Télécharger la copie originale',
  'wii.queueTitle': 'Pass à transférer',
  'wii.queueEmpty': "Aucun pour l'instant. Va dans l'onglet Pass et marque ceux que tu veux envoyer avec le rond de leur coin, ou en les maintenant appuyés.",
  'wii.noSlot': 'aucun emplacement',
  'wii.toSlot': '→ emplacement {n}',
  'wii.removeFromTransfer': 'Retirer du transfert',
  'wii.markOneMoreSlot': 'Marque {count} emplacement de plus ci-dessous : ils sont répartis dans l\'ordre où tu les touches.',
  'wii.markNMoreSlots': 'Marque {count} emplacements de plus ci-dessous : ils sont répartis dans l\'ordre où tu les touches.',
  'wii.allSlotsPaired': 'Chaque pass a déjà son emplacement. Vérifie les destinations avant de transférer.',
  'wii.passesInSave': 'Pass dans la sauvegarde ({used} sur {total} personnels)',
  'wii.design': 'design {n}',
  'wii.locked': 'verrouillé',
  'wii.unused': 'inutilisé',
  'wii.replaces': 'remplace {name}',
  'wii.theSlotN': "l'emplacement {n}",
  'wii.actions': 'Actions',
  'wii.saveNLocally': 'Enregistrer {n} en local',
  'wii.transfer': 'Transférer',
  'wii.transferNToSlots': 'Transférer {n} vers leurs emplacements',
  'wii.selectFirstHint': "Pour transférer, sélectionne d'abord des pass dans l'onglet Pass.",
  'wii.transferSummary': '{passes} · {slots} — {status}',
  'wii.nPassOne': '{n} pass',
  'wii.nPassMany': '{n} pass',
  'wii.nSlotOne': '{n} emplacement associé',
  'wii.nSlotMany': '{n} emplacements associés',
  'wii.missingOne': '{n} manquant',
  'wii.missingMany': '{n} manquants',
  'wii.allReady': 'tout est prêt',
  'wii.unlock': 'Déblocage',
  'wii.unlockHint': "Normalement, les emplacements de pass et les colisées se débloquent en jouant. Ceci le contourne.",
  'wii.unlockSlotsTitle': 'Débloquer les emplacements de pass',
  'wii.unlockSlotsBody': 'Les {n} emplacements de pass personnels de ce profil seront marqués comme disponibles.',
  'wii.unlock.button': 'Débloquer',
  'wii.slotsUnlocked': 'Emplacements de pass débloqués',
  'wii.allSlots': 'Tous les emplacements',
  'wii.unlockColosseumsTitle': 'Débloquer les colisées',
  'wii.unlockColosseumsBody': 'Les dix colisées seront marqués comme débloqués sur ce profil.',
  'wii.colosseumsUnlocked': 'Colisées débloqués',
  'wii.allColosseums': 'Tous les colisées',
  'wii.send': 'Envoyer',
  'wii.sendHint': "L'envoi recalcule les sommes de contrôle et augmente le compteur pour que le jeu préfère cette sauvegarde.",
  'wii.sessionOpenHint': "Tant que cet écran reste ouvert, aucun autre appareil ne peut modifier la sauvegarde. Appuie sur Fermer une fois terminé.",
  'wii.downloadSave': 'Télécharger la sauvegarde',
  'wii.sendToWiiTitle': 'Envoyer à la Wii',
  'wii.sendToWiiBody': "La sauvegarde de la Wii sera écrasée. Assure-toi d'avoir téléchargé la copie originale avant.",
  'wii.send.button': 'Envoyer',
  'wii.noSession': "Il n'y a pas de session ouverte avec la Wii",
  'wii.sendingToWii': 'Envoi de la sauvegarde à la Wii',
  'wii.sentToWii': 'Sauvegarde envoyée à la Wii',
  'wii.cannotSend': "Impossible d'envoyer",
  'wii.sendToWii': 'Envoyer à la Wii',
  'pokemoneditor.stat.hp': 'PV',
  'pokemoneditor.stat.atk': 'Att',
  'pokemoneditor.stat.def': 'Déf',
  'pokemoneditor.stat.spa': 'AtSp',
  'pokemoneditor.stat.spd': 'DéfSp',
  'pokemoneditor.stat.spe': 'Vit',
  'pokemoneditor.noItem': '— aucun —',
  'pokemoneditor.male': 'Mâle',
  'pokemoneditor.female': 'Femelle',
  'pokemoneditor.back': '‹ Retour',
  'pokemoneditor.noPidForGender': "Aucun PID de ce sexe n'a été trouvé pour ce Pokémon",
  'pokemoneditor.level': 'Niv. {level}',
  'pokemoneditor.shinyBadge': 'chromatique',
  'pokemoneditor.shinyLabel': 'Chromatique',
  'pokemoneditor.species': 'Espèce',
  'pokemoneditor.nickname': 'Surnom',
  'pokemoneditor.own': 'personnalisé',
  'pokemoneditor.nature': 'Nature',
  'pokemoneditor.noPidForNature': "Aucun PID avec cette nature n'a été trouvé pour ce Pokémon",
  'pokemoneditor.ability': 'Talent',
  'pokemoneditor.item': 'Objet',
  'pokemoneditor.pidNotHex': 'Le PID est constitué de 8 chiffres hexadécimaux',
  'pokemoneditor.random': 'Aléatoire',
  'pokemoneditor.pidHint': 'Il détermine la nature, le sexe et le talent utilisé par le jeu.',
  'pokemoneditor.abilityMismatch': '⚠ Le bit faible du PID demande {ability}. Le jeu respecte le talent enregistré, mais un vérificateur de légalité le signalerait.',
  'pokemoneditor.moves': 'Capacités',
  'pokemoneditor.recommended': 'Recommandées',
  'pokemoneditor.recommendedHint': 'celles que le jeu lui donnerait au niveau 50',
  'pokemoneditor.emptySlot': '— vide —',
  'pokemoneditor.allowIllegal': 'Autoriser les capacités illégales',
  'pokemoneditor.noDamagingMove': "Aucune capacité n'inflige de dégâts.",
  'pokemoneditor.stats': 'Statistiques',
  'pokemoneditor.statsHint': 'Les EV sont répartis (510 au total). Les IV sont fixes à la naissance : 31 est le maximum.',
  'pokemoneditor.ev': 'EV',
  'pokemoneditor.evOf510': 'EV : {total} / 510',
  'pokemoneditor.iv': 'IV',
  'pokemoneditor.ivSetTo31': 'IV mis à 31',
  'pokemoneditor.perfectIvs': 'IV parfaits',
  'pokemoneditor.ivSetRandom': 'IV aléatoires',
  'pokemoneditor.randomIvs': 'IV aléatoires',
  'pokemoneditor.warnings': 'Avertissements',
  'pokemoneditor.warningsHint': "Les avertissements n'empêchent pas d'enregistrer : le jeu acceptera le Pokémon quand même.",
  'generator.storageFull': 'Le stockage est plein (100 pass)',
  'generator.onlyRoomFor': 'Seulement {count} de la place : ceux-là seront générés',
  'generator.generatedOne': '{count} pass généré',
  'generator.generatedMany': '{count} pass générés',
  'generator.withSeed': '(graine {seed})',
  'generator.allNamed': '· tous nommés « {name} »',
  'generator.willBeCalledOne': 'Il s\'appellera « {name} »',
  'generator.willBeCalledMany': 'Ils s\'appelleront « {first} », « {second} »…',
  'generator.generateOne': 'Générer {count} pass',
  'generator.generateMany': 'Générer {count} pass',
  'generator.howMany': 'Combien',
  'generator.passCount': 'Nombre de pass',
  'generator.trainerName': 'Nom du dresseur',
  'generator.numberTokenHint': 'Écris {n} dans le nom, le numéro de chaque pass y sera inséré : « random{n} » donne random1, random2…',
  'generator.seed': 'Graine (facultatif)',
  'generator.seedPlaceholder': 'laisse vide pour un résultat différent à chaque fois',
  'generator.seedHint': 'La même graine produit exactement les mêmes pass : utile pour les partager sans envoyer de fichiers.',
  'generator.pokemon': 'Pokémon',
  'generator.moves': 'Capacités',
  'generator.moves.recommended': 'Recommandées',
  'generator.moves.legalRandom': 'Légales, mais aléatoires',
  'generator.moves.anything': 'Tout est permis',
  'generator.moves.hint': 'Toujours 4 capacités, et celles qui infligent des dégâts sont garanties sauf cas comme Métamorph.',
  'generator.damaging': 'Capacités offensives',
  'generator.damaging.one': 'Au moins une',
  'generator.damaging.two': 'Au moins deux',
  'generator.damaging.hint': 'Avec deux, les combats se résolvent plus vite ; avec une, il y a plus de variété et de curiosités.',
  'generator.sameTypeMove': 'Au moins une capacité de son type',
  'generator.sameTypeMove.hint': 'L\'une des quatre sera de l\'un des types du Pokémon, parmi celles qui infligent des dégâts si possible.',
  'generator.ivs': 'IV',
  'generator.ivs.perfect': 'Tous à 31',
  'generator.ivs.random': 'Aléatoires',
  'generator.evs': 'EV',
  'generator.evs.random': 'Aléatoires',
  'generator.evs.even': 'Répartis (85 chacun)',
  'generator.ability': 'Talent',
  'generator.ability.legal': 'L\'un des siens',
  'generator.ability.any': "N'importe lequel",
  'generator.item': 'Objet',
  'generator.item.none': 'Aucun',
  'generator.item.random': 'Aléatoire',
  'generator.evHint': "Les EV totalisent toujours les 510 complets, avec un maximum de 252 par statistique.",
  'generator.rules': 'Règles',
  'generator.atLeastOneLegendary': 'Au moins un légendaire',
  'generator.atLeastOneLegendary.hint': "Garantit que l'un des six est légendaire, semi-légendaire ou mythique.",
  'generator.onlyFinalForms': 'Uniquement les formes finales',
  'generator.onlyFinalForms.hint': "Écarte les stades qui évoluent encore. Les Pokémon sans ligne d'évolution, comme Tauros, restent inclus.",
  'generator.secret': 'Mode secret',
  'generator.secret.hint': 'Tu ne verras pas les Pokémon (« ? » s\'affichera) et ne pourras pas les modifier avant le transfert du pass sur la Wii.',
  'generator.chaosName': 'Chaos de surnom',
  'generator.chaosName.hint': 'Le même surnom pour tous les Pokémon du lot, même ceux de pass différents.',
  'generator.chaosNameText': 'Le surnom de tous',
  'generator.chaosNameText.placeholder': 'laisse vide pour un surnom aléatoire',
  'generator.chaosNameText.hint': "Vide : un mot espagnol aléatoire est demandé à un dictionnaire en ligne lors de la génération. Venant de l'extérieur, la graine ne le reproduit pas (hors ligne, un mot de la liste de secours est utilisé).",
  'generator.generating': 'Génération…',
  'generator.preview': 'Aperçu',
  'generator.previewHint': 'Un exemple avec les options actuelles :',
  'passeditor.phrase.greeting': 'Salutation',
  'passeditor.phrase.sentOut': "En envoyant un Pokémon",
  'passeditor.phrase.shift1': 'Changement 1',
  'passeditor.phrase.shift2': 'Changement 2',
  'passeditor.phrase.win': 'En cas de victoire',
  'passeditor.phrase.lose': 'En cas de défaite',
  'passeditor.back': '‹ Pass',
  'passeditor.secretMode': 'mode secret',
  'passeditor.trainerName': 'Nom du dresseur',
  'passeditor.trainerModel': 'Modèle de dresseur',
  'passeditor.trainerModelHint': "Changer de personnage restaure sa tenue par défaut : il n'est pas encore possible de choisir chaque vêtement individuellement.",
  'passeditor.selfIntroduction': 'Présentation',
  'passeditor.currentDesign': 'Design actuel : {design}. Le design se choisit lors du transfert vers la Wii, car il appartient à l\'emplacement de sauvegarde.',
  'passeditor.team': 'Équipe',
  'passeditor.secretBody': "Ce pass est en mode secret : il ne peut être vu ni modifié avant d'être transféré sur la Wii.",
  'passeditor.revealTitle': 'Révéler le pass',
  'passeditor.revealBody': 'Le mode secret sera désactivé et tu pourras voir et modifier les Pokémon. Impossible de le masquer à nouveau.',
  'passeditor.reveal': 'Révéler',
  'passeditor.revealed': 'Pass révélé',
  'passeditor.revealNow': 'Révéler maintenant',
  'passeditor.newPokemon': '+ Nouveau',
  'passeditor.fromOtherPass': "+ D'un autre pass",
  'passeditor.checksum': 'somme de contrôle',
  'passeditor.copyToOtherPass': 'Copier vers un autre pass',
  'passeditor.removePokemonTitle': 'Retirer le Pokémon',
  'passeditor.removePokemonBody': 'Retirer {name} du pass ?',
  'passeditor.remove': 'Retirer',
  'passeditor.phrases': 'Phrases',
  'passeditor.phrasesHint': 'Par défaut, le dresseur dit ce qui correspond à son personnage. Écrire sa propre phrase ne remplace que celle-ci.',
  'passeditor.presetPhrase': 'phrase par défaut du personnage',
  'passeditor.noPhrase': 'aucune phrase',
  'passeditor.resetToDefault': 'Revenir à celle par défaut',
  'passeditor.deletePassTitle': 'Supprimer le pass',
  'passeditor.deletePassBody': 'Supprimer « {name} » du stockage local ?',
  'passeditor.deletePass': 'Supprimer',
  'passeditor.deleteThisPass': 'Supprimer ce pass',
  'passlist.noPokemon': 'aucun Pokémon',
  'passlist.deselect': 'Retirer de la sélection',
  'passlist.select': 'Sélectionner',
  'passlist.selected': 'Sélectionné',
  'passlist.notSelected': 'Non sélectionné',
  'passlist.secret': 'secret',
  'passlist.storageFull': 'Le stockage est plein (100 pass)',
  'passlist.secretPassesTitle': 'Pass en mode secret',
  'passlist.secretPassesBody': '{count} des pass sont en mode secret. Une fois exportés, quiconque recevra le fichier pourra voir leur contenu. Continuer ?',
  'passlist.exportAnyway': 'Exporter quand même',
  'passlist.exportedOne': '{count} pass exporté',
  'passlist.exportedMany': '{count} pass exportés',
  'passlist.deleteTitle': 'Supprimer des pass',
  'passlist.deleteBodyOne': '{count} pass va être supprimé du stockage local. Cela n\'affecte rien sur la Wii.',
  'passlist.deleteBodyMany': '{count} pass vont être supprimés du stockage local. Cela n\'affecte rien sur la Wii.',
  'passlist.delete': 'Supprimer',
  'passlist.deletedOne': '{count} pass supprimé',
  'passlist.deletedMany': '{count} pass supprimés',
  'passlist.importPartial': 'Seulement {saved} sur {total} : le stockage est plein (100 pass)',
  'passlist.importedOne': '{count} pass importé',
  'passlist.importedMany': '{count} pass importés',
  'passlist.cannotReadFile': "Impossible de lire le fichier",
  'passlist.storedPasses': 'pass enregistrés',
  'passlist.import': 'Importer',
  'passlist.newPass': 'Nouveau pass',
  'passlist.generate': 'Générer',
  'passlist.emptyTitle': "Aucun pass enregistré pour l'instant.",
  'passlist.emptyBody': "Commence un pass vierge et construis toi-même l'équipe, génère-les au hasard, importe un fichier .aniapass ou lis ceux déjà présents sur la Wii.",
  'passlist.createPass': 'Créer un pass',
  'passlist.generateRandom': 'Générer au hasard',
  'passlist.nSelected': '{count} sélectionnés',
  'passlist.export': 'Exporter',
  'copymon.empty': 'vide',
  'copymon.noTarget': "Il n'y a pas d'autre pass où le copier",
  'copymon.copyTitle': 'Copier {name} vers un autre pass',
  'copymon.copyHint': 'Il reste aussi dans ce pass : c\'est une copie.',
  'copymon.copied': '{name} copié vers « {pass} »',
  'copymon.noSource': "Il n'y a pas d'autre pass avec des Pokémon à récupérer",
  'copymon.whichPass': 'De quel pass ?',
  'copymon.whichPokemon': 'Pokémon de « {pass} »',
  'copymon.bringHint': "Il est copié : l'autre pass garde le sien.",
};
