/** Italiano — traduzione automatica, revisione solo superficiale. */
export const it: Record<string, string> = {
  'state.noName': 'Senza nome',
  'main.tab.passes': 'Pass',
  'main.tab.generate': 'Genera',
  'main.tab.wii': 'Wii',
  'main.editPass': 'Modifica pass',
  'dom.accept': 'Accetta',
  'dom.cancel': 'Annulla',
  'dom.nothingToPick': 'Non c\'è nulla da scegliere.',
  'dom.preparing': 'Preparazione…',
  'dom.sizeOf': '{loaded} di {total}',
  'wii.phase.nand': 'La Wii sta leggendo il suo salvataggio…',
  'wii.phase.data': 'Trasferimento in corso…',
  'wii.phase.saving': 'La Wii sta scrivendo sulla NAND. Non spegnerla.',
  'wii.sessionLost': 'La sessione con la Wii è andata persa',
  'wii.busyTitle': 'La sessione è di un altro dispositivo',
  'wii.busyStale': 'Non dà segnali da {idle} s e scade da sola tra {remaining} s. Di solito è una scheda chiusa il cui avviso non è arrivato alla Wii: puoi prenderla ora.',
  'wii.busyActive': 'Un altro dispositivo sta modificando ed è ancora attivo (ultimo segnale {idle} s fa). Se davvero non c’è nessuno, si libererà tra {remaining} s.',
  'wii.takeover': 'Prendi il controllo',
  'wii.contactLost': 'Nessun contatto con la Wii; nuovo tentativo',
  'wii.contactBack': 'Contatto con la Wii ripristinato',
  'wii.releaseNote': 'Ultima chiusura: {when} ({event}) — {what}',
  'wii.releaseSent': 'avviso di chiusura inviato alla Wii',
  'wii.releaseFallback': 'il browser ha rifiutato il beacon; tentato con fetch',
  'wii.releaseNothing': 'non c’era nessuna sessione da rilasciare',
  'wii.enterAddress': "Scrivi l'indirizzo della Wii",
  'wii.badAddress': "Questo indirizzo non è valido. Scrivi l'IP della Wii o il suo nome (per esempio wii.local).",
  'wii.readingFromWii': 'Lettura del salvataggio della Wii',
  'wii.readFromWii': 'Salvataggio letto dalla Wii ({count} profili)',
  'wii.cannotConnect': 'Impossibile connettersi',
  'wii.loaded': 'Salvataggio caricato: {count} profili',
  'wii.notAPbrSave': 'Il file non è un salvataggio di PBR',
  'wii.savedLocally': '{count} pass salvati in locale',
  'wii.nothingSaved': 'Non è stato salvato nulla (pieno?)',
  'wii.selectInPassesTab': 'Seleziona i pass nella scheda Pass',
  'wii.chooseNSlots': 'Scegli {count} slot di destinazione',
  'wii.overwriteTitle': 'Stai per sovrascrivere dei pass',
  'wii.overwriteBody': '{count} degli slot scelti hanno già un pass: {names}. Andranno persi.',
  'wii.overwrite': 'Sovrascrivi',
  'wii.slotN': 'slot {n}',
  'wii.written': '{count} pass scritti nel salvataggio. Ricorda di inviarlo alla Wii.',
  'wii.save': 'Salvataggio',
  'wii.loadHint': "Carica il salvataggio da un file, oppure connettiti all'assistente Wii se è in esecuzione.",
  'wii.sameNetwork': 'Questo dispositivo deve trovarsi nella stessa rete locale della Wii.',
  'wii.wiiAddress': 'Indirizzo della Wii',
  'wii.port': 'Porta',
  'wii.connecting': 'Connessione in corso…',
  'wii.connect': 'Connetti alla Wii',
  'wii.openFile': 'Apri file',
  'wii.source': 'origine: {source}',
  'wii.editSessionOpen': 'sessione di modifica aperta',
  'wii.partition': 'partizione {n}',
  'wii.saveNumber': 'salvataggio n. {n}',
  'wii.gameVersion': 'versione {version} · {lang}',
  'wii.version.jp': 'giapponese',
  'wii.version.int': 'internazionale',
  'wii.profile': 'Profilo',
  'wii.emptyFile': 'File {n} (vuoto)',
  'wii.close': 'Chiudi',
  'wii.downloadBackup': 'Scarica copia originale',
  'wii.queueTitle': 'Pass da trasferire',
  'wii.queueEmpty': 'Ancora nessuno. Vai alla scheda Pass e segna quelli che vuoi inviare con il cerchietto nell\'angolo, o tenendoli premuti.',
  'wii.noSlot': 'nessuno slot',
  'wii.toSlot': '→ slot {n}',
  'wii.removeFromTransfer': 'Rimuovi dal trasferimento',
  'wii.markOneMoreSlot': 'Segna {count} altro slot qui sotto: vengono assegnati nell\'ordine in cui li tocchi.',
  'wii.markNMoreSlots': 'Segna {count} altri slot qui sotto: vengono assegnati nell\'ordine in cui li tocchi.',
  'wii.allSlotsPaired': 'Ogni pass ha già il suo slot. Controlla le destinazioni prima di trasferire.',
  'wii.passesInSave': 'Pass nel salvataggio ({used} di {total} personali)',
  'wii.design': 'design {n}',
  'wii.locked': 'bloccato',
  'wii.unused': 'inutilizzato',
  'wii.replaces': 'sostituisce {name}',
  'wii.theSlotN': 'lo slot {n}',
  'wii.actions': 'Azioni',
  'wii.saveNLocally': 'Salva {n} in locale',
  'wii.deleteNFromSave': 'Elimina {n} dal salvataggio',
  'wii.deleteTitle': 'Stai per eliminare dei pass',
  'wii.deleteBody': 'Verranno eliminati {count} pass dal salvataggio: {names}. Gli slot resteranno vuoti, con il loro design e il loro sblocco. Puoi annullare con la copia di sicurezza finché non invii il salvataggio.',
  'wii.delete': 'Elimina',
  'wii.deleted': '{count} pass eliminati dal salvataggio. Ricorda di inviarlo alla Wii.',
  'wii.nothingToDelete': 'Seleziona slot con un pass per eliminarli',
  'wii.transfer': 'Trasferisci',
  'wii.transferNToSlots': 'Trasferisci {n} ai loro slot',
  'wii.selectFirstHint': 'Per trasferire, seleziona prima i pass nella scheda Pass.',
  'wii.transferSummary': '{passes} · {slots} — {status}',
  'wii.nPassOne': '{n} pass',
  'wii.nPassMany': '{n} pass',
  'wii.nSlotOne': '{n} slot abbinato',
  'wii.nSlotMany': '{n} slot abbinati',
  'wii.missingOne': 'manca {n}',
  'wii.missingMany': 'mancano {n}',
  'wii.allReady': 'tutto pronto',
  'wii.unlock': 'Sblocco',
  'wii.unlockHint': 'Normalmente gli slot dei pass e i colossei si sbloccano giocando. Questo lo salta.',
  'wii.unlockSlotsTitle': 'Sblocca slot dei pass',
  'wii.unlockSlotsBody': 'I {n} slot di pass personali di questo profilo verranno segnati come disponibili.',
  'wii.unlock.button': 'Sblocca',
  'wii.slotsUnlocked': 'Slot dei pass sbloccati',
  'wii.allSlots': 'Tutti gli slot',
  'wii.unlockColosseumsTitle': 'Sblocca colossei',
  'wii.unlockColosseumsBody': 'I dieci colossei verranno segnati come sbloccati su questo profilo.',
  'wii.colosseumsUnlocked': 'Colossei sbloccati',
  'wii.allColosseums': 'Tutti i colossei',
  'wii.send': 'Invia',
  'wii.sendHint': 'Inviando si ricalcolano i checksum e si incrementa il contatore perché il gioco preferisca questa partita.',
  'wii.sessionOpenHint': 'Finché questa schermata resta aperta, nessun altro dispositivo può modificare il salvataggio. Premi Chiudi al termine.',
  'wii.downloadSave': 'Scarica salvataggio',
  'wii.sendToWiiTitle': 'Invia alla Wii',
  'wii.sendToWiiBody': 'Il salvataggio della Wii verrà sovrascritto. Assicurati di aver scaricato prima la copia originale.',
  'wii.send.button': 'Invia',
  'wii.noSession': 'Non c\'è una sessione aperta con la Wii',
  'wii.sendingToWii': 'Invio del salvataggio alla Wii',
  'wii.sentToWii': 'Salvataggio inviato alla Wii',
  'wii.cannotSend': 'Impossibile inviare',
  'wii.sendToWii': 'Invia alla Wii',
  'pokemoneditor.stat.hp': 'PS',
  'pokemoneditor.stat.atk': 'Att',
  'pokemoneditor.stat.def': 'Dif',
  'pokemoneditor.stat.spa': 'AttSp',
  'pokemoneditor.stat.spd': 'DifSp',
  'pokemoneditor.stat.spe': 'Vel',
  'pokemoneditor.noItem': '— nessuno —',
  'pokemoneditor.male': 'Maschio',
  'pokemoneditor.female': 'Femmina',
  'pokemoneditor.back': '‹ Indietro',
  'pokemoneditor.noPidForGender': 'Non è stato trovato un PID di quel sesso per questo Pokémon',
  'pokemoneditor.level': 'Liv. {level}',
  'pokemoneditor.shinyBadge': 'shiny',
  'pokemoneditor.shinyLabel': 'Shiny',
  'pokemoneditor.species': 'Specie',
  'pokemoneditor.nickname': 'Nomignolo',
  'pokemoneditor.own': 'proprio',
  'pokemoneditor.nature': 'Natura',
  'pokemoneditor.noPidForNature': 'Non è stato trovato un PID con quella natura per questo Pokémon',
  'pokemoneditor.ability': 'Abilità',
  'pokemoneditor.item': 'Oggetto',
  'pokemoneditor.pidNotHex': 'Il PID è composto da 8 cifre esadecimali',
  'pokemoneditor.random': 'Casuale',
  'pokemoneditor.pidHint': 'Da esso derivano la natura, il sesso e quale abilità usa il gioco.',
  'pokemoneditor.abilityMismatch': '⚠ Il bit basso del PID richiede {ability}. Il gioco rispetta l\'abilità salvata, ma un controllo di legalità la segnalerebbe.',
  'pokemoneditor.moves': 'Mosse',
  'pokemoneditor.recommended': 'Consigliate',
  'pokemoneditor.recommendedHint': 'quelle che il gioco gli darebbe al livello 50',
  'pokemoneditor.emptySlot': '— vuoto —',
  'pokemoneditor.allowIllegal': 'Permetti mosse illegali',
  'pokemoneditor.noDamagingMove': 'Nessuna mossa infligge danni.',
  'pokemoneditor.stats': 'Statistiche',
  'pokemoneditor.statsHint': 'Gli EV si distribuiscono (510 in totale). Gli IV sono fissi dalla nascita: 31 è il massimo.',
  'pokemoneditor.ev': 'EV',
  'pokemoneditor.evOf510': 'EV: {total} / 510',
  'pokemoneditor.iv': 'IV',
  'pokemoneditor.ivSetTo31': 'IV impostati a 31',
  'pokemoneditor.perfectIvs': 'IV perfetti',
  'pokemoneditor.ivSetRandom': 'IV casuali',
  'pokemoneditor.randomIvs': 'IV casuali',
  'pokemoneditor.warnings': 'Avvisi',
  'pokemoneditor.warningsHint': 'Gli avvisi non impediscono di salvare: il gioco accetterà comunque il Pokémon.',
  'generator.storageFull': 'Lo spazio è pieno (100 pass)',
  'generator.onlyRoomFor': 'C\'è posto solo per {count}: verranno generati quelli',
  'generator.generatedOne': '{count} pass generato',
  'generator.generatedMany': '{count} pass generati',
  'generator.withSeed': '(seme {seed})',
  'generator.allNamed': '· tutti si chiamano «{name}»',
  'generator.willBeCalledOne': 'Si chiamerà «{name}»',
  'generator.willBeCalledMany': 'Si chiameranno «{first}», «{second}»…',
  'generator.generateOne': 'Genera {count} pass',
  'generator.generateMany': 'Genera {count} pass',
  'generator.howMany': 'Quanti',
  'generator.passCount': 'Numero di pass',
  'generator.trainerName': 'Nome dell\'allenatore',
  'generator.numberTokenHint': 'Scrivi {n} nel nome e lì andrà il numero di ogni pass: «random{n}» dà random1, random2…',
  'generator.seed': 'Seme (opzionale)',
  'generator.seedPlaceholder': 'lascialo vuoto per uno diverso ogni volta',
  'generator.seedHint': 'Con lo stesso seme escono esattamente gli stessi pass: utile per condividerli senza inviare file.',
  'generator.pokemon': 'Pokémon',
  'generator.moves': 'Mosse',
  'generator.moves.recommended': 'Consigliate',
  'generator.moves.legalRandom': 'Legali, ma casuali',
  'generator.moves.anything': 'Tutto è permesso',
  'generator.moves.hint': 'Sempre 4 mosse, e quelle offensive sono garantite tranne casi come Ditto.',
  'generator.damaging': 'Mosse offensive',
  'generator.damaging.one': 'Almeno una',
  'generator.damaging.two': 'Almeno due',
  'generator.damaging.hint': 'Con due, i combattimenti si risolvono prima; con una c\'è più varietà e più rarità.',
  'generator.sameTypeMove': 'Almeno una mossa del suo tipo',
  'generator.sameTypeMove.hint': 'Una delle quattro sarà di uno dei tipi del Pokémon, tra quelle offensive se esiste.',
  'generator.ivs': 'IV',
  'generator.ivs.perfect': 'Tutti a 31',
  'generator.ivs.random': 'Casuali',
  'generator.evs': 'EV',
  'generator.evs.random': 'Casuali',
  'generator.evs.even': 'Equamente (85 ciascuno)',
  'generator.ability': 'Abilità',
  'generator.ability.legal': 'Una delle sue',
  'generator.ability.any': 'Qualsiasi',
  'generator.item': 'Oggetto',
  'generator.item.none': 'Nessuno',
  'generator.item.random': 'Casuale',
  'generator.evHint': 'Gli EV sommano sempre i 510 completi, con un massimo di 252 per statistica.',
  'generator.rules': 'Regole',
  'generator.atLeastOneLegendary': 'Almeno un leggendario',
  'generator.atLeastOneLegendary.hint': 'Garantisce che uno dei sei sia leggendario, semileggendario o mitico.',
  'generator.onlyFinalForms': 'Solo forme finali',
  'generator.onlyFinalForms.hint': 'Scarta le fasi che evolvono ancora. I Pokémon senza linea evolutiva, come Tauros, restano inclusi.',
  'generator.secret': 'Modalità segreta',
  'generator.secret.hint': 'Non vedrai i Pokémon (comparirà "?") né potrai modificarli finché il pass non viene trasferito sulla Wii.',
  'generator.chaosName': 'Caos di nomignolo',
  'generator.chaosName.hint': 'Lo stesso nomignolo per tutti i Pokémon del lotto, anche di pass diversi.',
  'generator.chaosNameText': 'Il nomignolo di tutti',
  'generator.chaosNameText.placeholder': 'lascialo vuoto ed esce a caso',
  'generator.chaosNameText.hint': 'Vuoto: alla generazione si chiede una parola spagnola casuale a un dizionario online. Venendo dall\'esterno, il seme non la riproduce (offline esce una dalla lista di riserva).',
  'generator.generating': 'Generazione…',
  'generator.preview': 'Anteprima',
  'generator.previewHint': 'Un esempio con le opzioni attuali:',
  'passeditor.phrase.greeting': 'Saluto',
  'passeditor.phrase.sentOut': 'Mandando in campo un Pokémon',
  'passeditor.phrase.shift1': 'Cambio 1',
  'passeditor.phrase.shift2': 'Cambio 2',
  'passeditor.phrase.win': 'Alla vittoria',
  'passeditor.phrase.lose': 'Alla sconfitta',
  'passeditor.back': '‹ Pass',
  'passeditor.secretMode': 'modalità segreta',
  'passeditor.trainerName': 'Nome dell\'allenatore',
  'passeditor.trainerModel': 'Modello dell\'allenatore',
  'passeditor.trainerModelHint': 'Cambiando personaggio si ripristina il suo vestiario predefinito: non è ancora possibile scegliere ogni capo singolarmente.',
  'passeditor.selfIntroduction': 'Autopresentazione',
  'passeditor.currentDesign': 'Design attuale: {design}. Il design si sceglie al trasferimento sulla Wii, perché appartiene allo slot di salvataggio.',
  'passeditor.team': 'Squadra',
  'passeditor.secretBody': 'Questo pass è in modalità segreta: non può essere visto né modificato finché non viene trasferito sulla Wii.',
  'passeditor.revealTitle': 'Rivela il pass',
  'passeditor.revealBody': 'La modalità segreta verrà disattivata e potrai vedere e modificare i Pokémon. Non si può nascondere di nuovo.',
  'passeditor.reveal': 'Rivela',
  'passeditor.revealed': 'Pass rivelato',
  'passeditor.revealNow': 'Rivela ora',
  'passeditor.newPokemon': '+ Nuovo',
  'passeditor.fromOtherPass': '+ Da un altro pass',
  'passeditor.checksum': 'checksum',
  'passeditor.copyToOtherPass': 'Copia in un altro pass',
  'passeditor.removePokemonTitle': 'Rimuovi Pokémon',
  'passeditor.removePokemonBody': 'Rimuovere {name} dal pass?',
  'passeditor.remove': 'Rimuovi',
  'passeditor.phrases': 'Frasi',
  'passeditor.phrasesHint': 'Di norma l\'allenatore dice ciò che si addice al suo personaggio. Scrivendo una frase propria si sostituisce solo quella.',
  'passeditor.presetPhrase': 'frase predefinita del personaggio',
  'passeditor.noPhrase': 'nessuna frase',
  'passeditor.resetToDefault': 'Torna a quella predefinita',
  'passeditor.deletePassTitle': 'Elimina pass',
  'passeditor.deletePassBody': 'Eliminare "{name}" dallo spazio locale?',
  'passeditor.deletePass': 'Elimina',
  'passeditor.deleteThisPass': 'Elimina questo pass',
  'passlist.noPokemon': 'nessun Pokémon',
  'passlist.deselect': 'Rimuovi dalla selezione',
  'passlist.select': 'Seleziona',
  'passlist.selected': 'Selezionato',
  'passlist.notSelected': 'Non selezionato',
  'passlist.secret': 'segreto',
  'passlist.storageFull': 'Lo spazio è pieno (100 pass)',
  'passlist.secretPassesTitle': 'Pass in modalità segreta',
  'passlist.secretPassesBody': '{count} dei pass sono in modalità segreta. Una volta esportati, chi riceve il file potrà vederne il contenuto. Continuare?',
  'passlist.exportAnyway': 'Esporta comunque',
  'passlist.exportedOne': '{count} pass esportato',
  'passlist.exportedMany': '{count} pass esportati',
  'passlist.deleteTitle': 'Elimina pass',
  'passlist.deleteBodyOne': '{count} pass verrà eliminato dallo spazio locale. Non incide su nulla della Wii.',
  'passlist.deleteBodyMany': '{count} pass verranno eliminati dallo spazio locale. Non incide su nulla della Wii.',
  'passlist.delete': 'Elimina',
  'passlist.deletedOne': '{count} pass eliminato',
  'passlist.deletedMany': '{count} pass eliminati',
  'passlist.importPartial': 'C\'è posto solo per {saved} di {total}: lo spazio è pieno (100 pass)',
  'passlist.importedOne': '{count} pass importato',
  'passlist.importedMany': '{count} pass importati',
  'passlist.cannotReadFile': 'Non è stato possibile leggere il file',
  'passlist.storedPasses': 'pass salvati',
  'passlist.import': 'Importa',
  'passlist.newPass': 'Nuovo pass',
  'passlist.generate': 'Genera',
  'passlist.emptyTitle': 'Ancora nessun pass salvato.',
  'passlist.emptyBody': 'Inizia un pass vuoto e crea tu la squadra, generali a caso, importa un file .aniapass o leggi quelli già presenti sulla Wii.',
  'passlist.createPass': 'Crea un pass',
  'passlist.generateRandom': 'Genera a caso',
  'passlist.nSelected': '{count} selezionati',
  'passlist.export': 'Esporta',
  'copymon.empty': 'vuoto',
  'copymon.noTarget': 'Non c\'è un altro pass dove copiarlo',
  'copymon.copyTitle': 'Copia {name} in un altro pass',
  'copymon.copyHint': 'Resta anche in questo pass: è una copia.',
  'copymon.copied': '{name} copiato in «{pass}»',
  'copymon.noSource': 'Non c\'è un altro pass con Pokémon da portare',
  'copymon.whichPass': 'Da quale pass?',
  'copymon.whichPokemon': 'Pokémon da «{pass}»',
  'copymon.bringHint': 'Viene copiato: l\'altro pass mantiene il suo.',
};
