/**
 * 日本語 — para los guardados de la versión japonesa (RPBJ01).
 *
 * Las claves y el orden son los del castellano (`es.ts`), que es el idioma de referencia.
 */
export const ja: Record<string, string> = {
  'state.noName': '名前なし',
  'main.tab.passes': 'パス',
  'main.tab.generate': '生成',
  'main.tab.wii': 'Wii',
  'main.editPass': 'パスを編集',
  'dom.accept': 'OK',
  'dom.cancel': 'キャンセル',
  'dom.nothingToPick': '選べるものがありません。',
  'dom.preparing': '準備中…',
  'dom.sizeOf': '{total} 中 {loaded}',
  'wii.phase.nand': 'Wii がセーブデータを読み込んでいます…',
  'wii.phase.data': '転送中…',
  'wii.phase.saving': 'Wii が NAND に書き込んでいます。電源を切らないでください。',
  'wii.sessionLost': 'Wii とのセッションが切れました',
  'wii.busyTitle': 'ほかの端末がセッションを持っています',
  'wii.busyStale': '{idle} 秒応答がなく、あと {remaining} 秒で自動的に期限切れになります。たいていは閉じたタブの通知が Wii に届かなかっただけです。いま引き継げます。',
  'wii.busyActive': 'ほかの端末が編集中で、まだ動いています（最後の応答は {idle} 秒前）。本当に誰もいなければ、あと {remaining} 秒で空きます。',
  'wii.takeover': 'セッションを引き継ぐ',
  'wii.contactLost': 'Wii と連絡が取れません。再試行しています',
  'wii.contactBack': 'Wii との連絡が回復しました',
  'wii.releaseNote': '前回の終了：{when}（{event}）— {what}',
  'wii.releaseSent': '終了の通知を Wii に送信しました',
  'wii.releaseFallback': 'ブラウザが beacon を拒否したため fetch で試しました',
  'wii.releaseNothing': '解放するセッションはありませんでした',
  'wii.enterAddress': 'Wii のアドレスを入力してください',
  'wii.badAddress': 'そのアドレスは使えません。Wii の IP か名前（たとえば wii.local）を入力してください。',
  'wii.readingFromWii': 'Wii のセーブデータを読み込み中',
  'wii.readFromWii': 'Wii からセーブデータを読み込みました（{count} プロフィール）',
  'wii.cannotConnect': '接続できませんでした',
  'wii.loaded': 'セーブデータを読み込みました：{count} プロフィール',
  'wii.notAPbrSave': 'このファイルは PBR のセーブデータではありません',
  'wii.savedLocally': '{count} 件のパスを端末に保存しました',
  'wii.nothingSaved': '何も保存できませんでした（保存領域がいっぱい？）',
  'wii.selectInPassesTab': '「パス」タブでパスを選んでください',
  'wii.chooseNSlots': '転送先の枠を {count} 個選んでください',
  'wii.overwriteTitle': 'パスを上書きします',
  'wii.overwriteBody': '選んだ枠のうち {count} 個にはすでにパスがあります：{names}。失われます。',
  'wii.overwrite': '上書きする',
  'wii.slotN': '枠 {n}',
  'wii.written': '{count} 件のパスをセーブデータに書き込みました。Wii への送信を忘れずに。',
  'wii.save': 'セーブデータ',
  'wii.loadHint': 'ファイルからセーブデータを読み込むか、Wii アシスタントが動いていれば接続してください。',
  'wii.sameNetwork': 'この端末は Wii と同じローカルネットワークに接続されている必要があります。',
  'wii.wiiAddress': 'Wii のアドレス',
  'wii.port': 'ポート',
  'wii.connecting': '接続中…',
  'wii.connect': 'Wii に接続',
  'wii.openFile': 'ファイルを開く',
  'wii.source': '取得元：{source}',
  'wii.editSessionOpen': '編集セッション中',
  'wii.partition': 'パーティション {n}',
  'wii.saveNumber': 'セーブ回数 {n}',
  'wii.gameVersion': '{version}・{lang}',
  'wii.version.jp': '日本語版',
  'wii.version.int': '海外版',
  'wii.profile': 'プロフィール',
  'wii.emptyFile': 'ファイル {n}（空）',
  'wii.close': '閉じる',
  'wii.downloadBackup': '元のコピーをダウンロード',
  'wii.queueTitle': '転送するパス',
  'wii.queueEmpty': 'まだありません。「パス」タブで、角の丸印を押すか長押しして送りたいパスを選んでください。',
  'wii.noSlot': '枠なし',
  'wii.toSlot': '→ 枠 {n}',
  'wii.removeFromTransfer': '転送から外す',
  'wii.markOneMoreSlot': '下であと {count} 個の枠を選んでください。触れた順に割り当てられます。',
  'wii.markNMoreSlots': '下であと {count} 個の枠を選んでください。触れた順に割り当てられます。',
  'wii.allSlotsPaired': 'すべてのパスに枠が決まりました。転送前に行き先を確認してください。',
  'wii.passesInSave': 'セーブデータ内のパス（自分用 {total} 件中 {used} 件）',
  'wii.design': 'デザイン {n}',
  'wii.locked': 'ロック中',
  'wii.unused': '未使用',
  'wii.replaces': '{name} と置き換え',
  'wii.theSlotN': '枠 {n}',
  'wii.actions': '操作',
  'wii.saveNLocally': '{n} 件を端末に保存',
  'wii.deleteNFromSave': '{n} 件をセーブデータから削除',
  'wii.deleteTitle': 'パスを削除します',
  'wii.deleteBody': 'セーブデータから {count} 件のパスを削除します：{names}。枠はデザインと解放状態を残したまま空になります。セーブデータを送信するまでは、バックアップで元に戻せます。',
  'wii.delete': '削除する',
  'wii.deleted': '{count} 件のパスをセーブデータから削除しました。Wii に送信するのを忘れずに。',
  'wii.nothingToDelete': '削除するには、パスの入った枠を選んでください',
  'wii.transfer': '転送',
  'wii.transferNToSlots': '{n} 件をそれぞれの枠へ転送',
  'wii.selectFirstHint': '転送するには、先に「パス」タブでパスを選んでください。',
  'wii.transferSummary': '{passes}・{slots} — {status}',
  'wii.nPassOne': 'パス {n} 件',
  'wii.nPassMany': 'パス {n} 件',
  'wii.nSlotOne': '枠 {n} 個を割り当て済み',
  'wii.nSlotMany': '枠 {n} 個を割り当て済み',
  'wii.missingOne': 'あと {n} 個',
  'wii.missingMany': 'あと {n} 個',
  'wii.allReady': '準備完了',
  'wii.unlock': '解放',
  'wii.unlockHint': '本来、パスの枠とコロシアムはプレイして解放します。これはそれを飛ばします。',
  'wii.unlockSlotsTitle': 'パスの枠を解放',
  'wii.unlockSlotsBody': 'このプロフィールの自分用パスの枠 {n} 個を使用可能にします。',
  'wii.unlock.button': '解放する',
  'wii.slotsUnlocked': 'パスの枠を解放しました',
  'wii.allSlots': 'すべての枠',
  'wii.unlockColosseumsTitle': 'コロシアムを解放',
  'wii.unlockColosseumsBody': 'このプロフィールの 10 か所のコロシアムを解放済みにします。',
  'wii.colosseumsUnlocked': 'コロシアムを解放しました',
  'wii.allColosseums': 'すべてのコロシアム',
  'wii.send': '送信',
  'wii.sendHint': '送信時にチェックサムを計算し直し、ゲームがこのデータを選ぶようにセーブ回数を増やします。',
  'wii.sessionOpenHint': 'この画面を開いているあいだ、ほかの端末はセーブデータを編集できません。終わったら「閉じる」を押してください。',
  'wii.downloadSave': 'セーブデータをダウンロード',
  'wii.sendToWiiTitle': 'Wii に送信',
  'wii.sendToWiiBody': 'Wii のセーブデータを上書きします。先に元のコピーをダウンロードしておいてください。',
  'wii.send.button': '送信する',
  'wii.noSession': 'Wii とのセッションがありません',
  'wii.sendingToWii': 'Wii にセーブデータを送信中',
  'wii.sentToWii': 'Wii にセーブデータを送信しました',
  'wii.cannotSend': '送信できませんでした',
  'wii.sendToWii': 'Wii に送信',
  'pokemoneditor.stat.hp': 'HP',
  'pokemoneditor.stat.atk': 'こうげき',
  'pokemoneditor.stat.def': 'ぼうぎょ',
  'pokemoneditor.stat.spa': 'とくこう',
  'pokemoneditor.stat.spd': 'とくぼう',
  'pokemoneditor.stat.spe': 'すばやさ',
  'pokemoneditor.noItem': '— なし —',
  'pokemoneditor.male': 'オス',
  'pokemoneditor.female': 'メス',
  'pokemoneditor.back': '‹ 戻る',
  'pokemoneditor.noPidForGender': 'このポケモンでその性別になる PID が見つかりませんでした',
  'pokemoneditor.level': 'Lv. {level}',
  'pokemoneditor.shinyBadge': '色違い',
  'pokemoneditor.shinyLabel': '色違い',
  'pokemoneditor.species': 'ポケモン',
  'pokemoneditor.nickname': 'ニックネーム',
  'pokemoneditor.own': '独自',
  'pokemoneditor.nature': 'せいかく',
  'pokemoneditor.noPidForNature': 'このポケモンでその性格になる PID が見つかりませんでした',
  'pokemoneditor.ability': 'とくせい',
  'pokemoneditor.item': 'もちもの',
  'pokemoneditor.pidNotHex': 'PID は 16 進数 8 桁です',
  'pokemoneditor.random': 'ランダム',
  'pokemoneditor.pidHint': '性格・性別・ゲームが使う特性は、すべてここから決まります。',
  'pokemoneditor.abilityMismatch': '⚠ PID の下位ビットは {ability} を指しています。ゲームは保存された特性を優先しますが、合法性チェッカーは警告します。',
  'pokemoneditor.moves': 'わざ',
  'pokemoneditor.recommended': 'おすすめ',
  'pokemoneditor.recommendedHint': 'レベル 50 でゲームが覚えさせるわざ',
  'pokemoneditor.emptySlot': '— なし —',
  'pokemoneditor.allowIllegal': '覚えられないわざも許可',
  'pokemoneditor.noDamagingMove': 'ダメージを与えるわざがありません。',
  'pokemoneditor.stats': 'のうりょく',
  'pokemoneditor.statsHint': '努力値は合計 510 まで振り分けます。個体値は生まれつきで、31 が最大です。',
  'pokemoneditor.ev': '努力値',
  'pokemoneditor.evOf510': '努力値：{total} / 510',
  'pokemoneditor.iv': '個体値',
  'pokemoneditor.ivSetTo31': '個体値を 31 にしました',
  'pokemoneditor.perfectIvs': '個体値を最大に',
  'pokemoneditor.ivSetRandom': '個体値をランダムにしました',
  'pokemoneditor.randomIvs': '個体値をランダムに',
  'pokemoneditor.warnings': '警告',
  'pokemoneditor.warningsHint': '警告があっても保存できます。ゲームはこのポケモンを受け付けます。',
  'generator.storageFull': '保存領域がいっぱいです（100 件）',
  'generator.onlyRoomFor': 'あと {count} 件しか入りません。その分だけ生成します',
  'generator.generatedOne': 'パスを {count} 件生成しました',
  'generator.generatedMany': 'パスを {count} 件生成しました',
  'generator.withSeed': '（シード {seed}）',
  'generator.allNamed': '・全員のニックネームは「{name}」',
  'generator.willBeCalledOne': '名前は「{name}」になります',
  'generator.willBeCalledMany': '名前は「{first}」「{second}」…になります',
  'generator.generateOne': 'パスを {count} 件生成',
  'generator.generateMany': 'パスを {count} 件生成',
  'generator.howMany': '件数',
  'generator.passCount': 'パスの数',
  'generator.trainerName': 'トレーナー名',
  'generator.numberTokenHint': '名前に {n} と書くと、そこに各パスの番号が入ります：「random{n}」なら random1、random2…',
  'generator.seed': 'シード（任意）',
  'generator.seedPlaceholder': '空にすると毎回変わります',
  'generator.seedHint': '同じシードならまったく同じパスが出ます。ファイルを送らずに共有できます。',
  'generator.pokemon': 'ポケモン',
  'generator.moves': 'わざ',
  'generator.moves.recommended': 'おすすめ',
  'generator.moves.legalRandom': '覚えられるわざからランダム',
  'generator.moves.anything': 'なんでもあり',
  'generator.moves.hint': 'わざは必ず 4 つ。ダメージわざは、メタモンのような例外を除いて保証されます。',
  'generator.damaging': 'ダメージを与えるわざ',
  'generator.damaging.one': '最低 1 つ',
  'generator.damaging.two': '最低 2 つ',
  'generator.damaging.hint': '2 つなら勝負が早く決まり、1 つなら変わった構成が増えます。',
  'generator.sameTypeMove': '自分のタイプのわざを最低 1 つ',
  'generator.sameTypeMove.hint': '4 つのうち 1 つはそのポケモンのタイプのわざになります。あればダメージわざを優先します。',
  'generator.ivs': '個体値',
  'generator.ivs.perfect': 'すべて 31',
  'generator.ivs.random': 'ランダム',
  'generator.evs': '努力値',
  'generator.evs.random': 'ランダム',
  'generator.evs.even': '均等（各 85）',
  'generator.ability': 'とくせい',
  'generator.ability.legal': '本来のものから',
  'generator.ability.any': 'なんでも',
  'generator.item': 'もちもの',
  'generator.item.none': 'なし',
  'generator.item.random': 'ランダム',
  'generator.evHint': '努力値は常に合計 510 ちょうどになり、1 つのステータスにつき最大 252 です。',
  'generator.rules': 'ルール',
  'generator.atLeastOneLegendary': '伝説を最低 1 匹',
  'generator.atLeastOneLegendary.hint': '6 匹のうち 1 匹が伝説・準伝説・幻のポケモンになります。',
  'generator.onlyFinalForms': '最終進化のみ',
  'generator.onlyFinalForms.hint': 'まだ進化を残す段階を除きます。ケンタロスのように進化しないポケモンはそのまま入ります。',
  'generator.secret': 'シークレットモード',
  'generator.secret.hint': 'Wii にパスを転送するまで、ポケモンは「?」で表示され、編集もできません。',
  'generator.chaosName': 'ニックネーム混乱',
  'generator.chaosName.hint': '生成したすべてのポケモンに、パスをまたいで同じニックネームを付けます。',
  'generator.chaosNameText': '全員のニックネーム',
  'generator.chaosNameText.placeholder': '空にするとランダムになります',
  'generator.chaosNameText.hint': '空の場合、生成時にインターネットの辞書からスペイン語の単語をランダムに取ります。外から来る単語なので、シードでは再現できません（接続がなければ内蔵の予備リストから選びます）。',
  'generator.generating': '生成中…',
  'generator.preview': 'プレビュー',
  'generator.previewHint': '今の設定での一例：',
  'passeditor.phrase.greeting': 'あいさつ',
  'passeditor.phrase.sentOut': 'ポケモンを出すとき',
  'passeditor.phrase.shift1': '交代 1',
  'passeditor.phrase.shift2': '交代 2',
  'passeditor.phrase.win': '勝ったとき',
  'passeditor.phrase.lose': '負けたとき',
  'passeditor.back': '‹ パス',
  'passeditor.secretMode': 'シークレットモード',
  'passeditor.trainerName': 'トレーナー名',
  'passeditor.trainerModel': 'トレーナーのすがた',
  'passeditor.trainerModelHint': 'キャラクターを変えると服装が初期状態に戻ります。今のところ 1 点ずつは選べません。',
  'passeditor.selfIntroduction': '自己紹介',
  'passeditor.currentDesign': '現在のデザイン：{design}。デザインはセーブデータの枠に属するので、Wii へ転送するときに決まります。',
  'passeditor.team': 'てもち',
  'passeditor.secretBody': 'このパスはシークレットモードです。Wii に転送するまで、見ることも編集することもできません。',
  'passeditor.revealTitle': 'パスを公開',
  'passeditor.revealBody': 'シークレットモードを解除すると、ポケモンを見て編集できます。もう一度隠すことはできません。',
  'passeditor.reveal': '公開する',
  'passeditor.revealed': 'パスを公開しました',
  'passeditor.revealNow': 'いま公開する',
  'passeditor.newPokemon': '+ 新規',
  'passeditor.fromOtherPass': '+ ほかのパスから',
  'passeditor.checksum': 'チェックサム',
  'passeditor.copyToOtherPass': 'ほかのパスへコピー',
  'passeditor.removePokemonTitle': 'ポケモンを外す',
  'passeditor.removePokemonBody': '{name} をこのパスから外しますか？',
  'passeditor.remove': '外す',
  'passeditor.phrases': 'セリフ',
  'passeditor.phrasesHint': '初期状態では、トレーナーはそのキャラクター用のセリフを話します。自分でセリフを書くと、そのセリフだけが置き換わります。',
  'passeditor.presetPhrase': 'キャラクター既定のセリフ',
  'passeditor.noPhrase': 'セリフなし',
  'passeditor.resetToDefault': '既定に戻す',
  'passeditor.deletePassTitle': 'パスを削除',
  'passeditor.deletePassBody': '「{name}」を端末の保存領域から削除しますか？',
  'passeditor.deletePass': '削除',
  'passeditor.deleteThisPass': 'このパスを削除',
  'passlist.noPokemon': 'ポケモンなし',
  'passlist.deselect': '選択を解除',
  'passlist.select': '選択',
  'passlist.selected': '選択中',
  'passlist.notSelected': '未選択',
  'passlist.secret': 'シークレット',
  'passlist.storageFull': '保存領域がいっぱいです（100 件）',
  'passlist.secretPassesTitle': 'シークレットモードのパス',
  'passlist.secretPassesBody': '{count} 件がシークレットモードです。書き出すと、ファイルを受け取った人は中身を見られます。続けますか？',
  'passlist.exportAnyway': 'それでも書き出す',
  'passlist.exportedOne': 'パスを {count} 件書き出しました',
  'passlist.exportedMany': 'パスを {count} 件書き出しました',
  'passlist.deleteTitle': 'パスを削除',
  'passlist.deleteBodyOne': '端末の保存領域からパスを {count} 件削除します。Wii の中身には影響しません。',
  'passlist.deleteBodyMany': '端末の保存領域からパスを {count} 件削除します。Wii の中身には影響しません。',
  'passlist.delete': '削除',
  'passlist.deletedOne': 'パスを {count} 件削除しました',
  'passlist.deletedMany': 'パスを {count} 件削除しました',
  'passlist.importPartial': '{total} 件中 {saved} 件しか入りません：保存領域がいっぱいです（100 件）',
  'passlist.importedOne': 'パスを {count} 件読み込みました',
  'passlist.importedMany': 'パスを {count} 件読み込みました',
  'passlist.cannotReadFile': 'ファイルを読み込めませんでした',
  'passlist.storedPasses': '保存済みのパス',
  'passlist.import': '読み込む',
  'passlist.newPass': '新しいパス',
  'passlist.generate': '生成',
  'passlist.emptyTitle': 'まだ保存されたパスがありません。',
  'passlist.emptyBody': '空のパスから自分で組むか、ランダムに生成するか、.aniapass ファイルを読み込むか、Wii にあるパスを読み込んでください。',
  'passlist.createPass': 'パスを作る',
  'passlist.generateRandom': 'ランダムに生成',
  'passlist.nSelected': '{count} 件を選択中',
  'passlist.export': '書き出す',
  'copymon.empty': '空',
  'copymon.noTarget': 'コピー先になるパスがありません',
  'copymon.copyTitle': '{name} をほかのパスへコピー',
  'copymon.copyHint': 'このパスにも残ります。コピーです。',
  'copymon.copied': '{name} を「{pass}」にコピーしました',
  'copymon.noSource': '連れてこられるポケモンのいるパスがありません',
  'copymon.whichPass': 'どのパスから？',
  'copymon.whichPokemon': '「{pass}」のポケモン',
  'copymon.bringHint': 'コピーです。元のパスにもそのまま残ります。',
};
